// Hebrew idioms data for Advanced Conjugation game mode.
// Each entry exposes a normalized shape used by advConj functions in app.js:
//   present_tense  — alias for conjugations.present
//   past_tense     — alias for conjugations.past
//   future_tense   — alias for conjugations.future
//   english_meaning — alias for english
const HEBREW_IDIOMS = (function () {
  const raw = [
  {
    "id": "shaga",
    "level": 1,
    "infinitive": "לשגע מישהו",
    "english": "to drive someone crazy",
    "verb": "לשגע",
    "root": "ש.ג.ע",
    "binyan": "piel",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "אתה משגע אותי",
    "negated": false,
    "literal_sg": "{s} drives {o} crazy",
    "literal_pl": "{s} drive {o} crazy",
    "literal_past": "{s} drove {o} crazy",
    "literal_future": "{s} will drive {o} crazy",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "משגע", "fsg": "משגעת", "mpl": "משגעים", "fpl": "משגעות" },
      "past":    { "msg": "שיגע", "fsg": "שיגעה", "mpl": "שיגעו", "fpl": "שיגעו" },
      "future":  { "msg": "ישגע", "fsg": "תשגע", "mpl": "ישגעו", "fpl": "ישגעו" }
    }
  },
  {
    "id": "itzben",
    "level": 1,
    "infinitive": "לעצבן מישהו",
    "english": "to annoy someone",
    "verb": "לעצבן",
    "root": "ע.צ.ב.נ",
    "binyan": "piel",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "אתה מעצבן אותי",
    "negated": false,
    "literal_sg": "{s} annoys {o}",
    "literal_pl": "{s} annoy {o}",
    "literal_past": "{s} annoyed {o}",
    "literal_future": "{s} will annoy {o}",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "מעצבן", "fsg": "מעצבנת", "mpl": "מעצבנים", "fpl": "מעצבנות" },
      "past":    { "msg": "עיצבן", "fsg": "עיצבנה", "mpl": "עיצבנו", "fpl": "עיצבנו" },
      "future":  { "msg": "יעצבן", "fsg": "תעצבן", "mpl": "יעצבנו", "fpl": "יעצבנו" }
    }
  },
  {
    "id": "hidlik",
    "level": 1,
    "infinitive": "להדליק מישהו",
    "english": "to excite / turn someone on",
    "verb": "להדליק",
    "root": "ד.ל.ק",
    "binyan": "hifil",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "אתה מדליק אותי",
    "negated": false,
    "literal_sg": "{s} lights {o} up",
    "literal_pl": "{s} light {o} up",
    "literal_past": "{s} lit {o} up",
    "literal_future": "{s} will light {o} up",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מדליק", "fsg": "מדליקה", "mpl": "מדליקים", "fpl": "מדליקות" },
      "past":    { "msg": "הדליק", "fsg": "הדליקה", "mpl": "הדליקו", "fpl": "הדליקו" },
      "future":  { "msg": "ידליק", "fsg": "תדליק", "mpl": "ידליקו", "fpl": "ידליקו" }
    },
    "conjugations_niqqud": {
      "present": { "msg": "מַדְלִיק", "fsg": "מַדְלִיקָה", "mpl": "מַדְלִיקִים", "fpl": "מַדְלִיקוֹת" },
      "past":    { "msg": "הִדְלִיק", "fsg": "הִדְלִיקָה", "mpl": "הִדְלִיקוּ", "fpl": "הִדְלִיקוּ" },
      "future":  { "msg": "יַדְלִיק", "fsg": "תַּדְלִיק", "mpl": "יַדְלִיקוּ", "fpl": "יַדְלִיקוּ" }
    },
    "niqqud_status": "reviewed",
    "niqqud_sources": ["https://www.pealim.com/dict/423-lehadlik/"]
  },
  {
    "id": "hitrif",
    "level": 1,
    "infinitive": "להטריף מישהו",
    "english": "to drive someone insane",
    "verb": "להטריף",
    "root": "ט.ר.פ",
    "binyan": "hifil",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "אתה מטריף אותי",
    "negated": false,
    "literal_sg": "{s} drives {o} insane",
    "literal_pl": "{s} drive {o} insane",
    "literal_past": "{s} drove {o} insane",
    "literal_future": "{s} will drive {o} insane",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "מטריף", "fsg": "מטריפה", "mpl": "מטריפים", "fpl": "מטריפות" },
      "past":    { "msg": "הטריף", "fsg": "הטריפה", "mpl": "הטריפו", "fpl": "הטריפו" },
      "future":  { "msg": "יטריף", "fsg": "תטריף", "mpl": "יטריפו", "fpl": "יטריפו" }
    }
  },
  {
    "id": "kara",
    "level": 1,
    "infinitive": "לקרוע מישהו",
    "english": "to kill/send someone [funny]",
    "verb": "לקרוע",
    "root": "ק.ר.ע",
    "binyan": "paal",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "הוא קורע אותי",
    "negated": false,
    "literal_sg": "{s} tears {o}",
    "literal_pl": "{s} tear {o}",
    "literal_past": "{s} tore {o}",
    "literal_future": "{s} will tear {o}",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "קורע", "fsg": "קורעת", "mpl": "קורעים", "fpl": "קורעות" },
      "past":    { "msg": "קרע", "fsg": "קרעה", "mpl": "קרעו", "fpl": "קרעו" },
      "future":  { "msg": "יקרע", "fsg": "תקרע", "mpl": "יקרעו", "fpl": "יקרעו" }
    }
  },
  {
    "id": "haalat_sif",
    "level": 2,
    "infinitive": "להעלות למישהו את הסעיף",
    "english": "to drive someone up the wall",
    "verb": "להעלות",
    "root": "ע.ל.ה",
    "binyan": "hifil",
    "object_type": "l_dative",
    "fixed_object": "את הסעיף",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את הסעיף",
    "example": "אתה מעלה לי את הסעיף",
    "negated": false,
    "literal_sg": "{s} raises {p} paragraph",
    "literal_pl": "{s} raise {p} paragraph",
    "literal_past": "{s} raised {p} paragraph",
    "literal_future": "{s} will raise {p} paragraph",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מעלה", "fsg": "מעלה", "mpl": "מעלים", "fpl": "מעלות" },
      "past":    { "msg": "העלה", "fsg": "העלתה", "mpl": "העלו", "fpl": "העלו" },
      "future":  { "msg": "יעלה", "fsg": "תעלה", "mpl": "יעלו", "fpl": "יעלו" }
    }
  },
  {
    "id": "horadat_hesheq",
    "level": 2,
    "infinitive": "להוריד למישהו את החשק",
    "english": "to kill someone's motivation",
    "verb": "להוריד",
    "root": "י.ר.ד",
    "binyan": "hifil",
    "object_type": "l_dative",
    "fixed_object": "את החשק",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את החשק",
    "example": "אתה מוריד לי את החשק",
    "negated": false,
    "literal_sg": "{s} brings down {p} desire",
    "literal_pl": "{s} bring down {p} desire",
    "literal_past": "{s} brought down {p} desire",
    "literal_future": "{s} will bring down {p} desire",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מוריד", "fsg": "מורידה", "mpl": "מורידים", "fpl": "מורידות" },
      "past":    { "msg": "הוריד", "fsg": "הורידה", "mpl": "הורידו", "fpl": "הורידו" },
      "future":  { "msg": "יוריד", "fsg": "תוריד", "mpl": "יורידו", "fpl": "יורידו" }
    }
  },
  {
    "id": "hotzaat_mitz",
    "level": 2,
    "infinitive": "להוציא למישהו את המיץ",
    "english": "to exhaust / wear someone out",
    "verb": "להוציא",
    "root": "י.צ.א",
    "binyan": "hifil",
    "object_type": "l_dative",
    "fixed_object": "את המיץ",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את המיץ",
    "example": "אתה מוציא לי את המיץ",
    "negated": false,
    "literal_sg": "{s} takes out {p} juice",
    "literal_pl": "{s} take out {p} juice",
    "literal_past": "{s} took out {p} juice",
    "literal_future": "{s} will take out {p} juice",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מוציא", "fsg": "מוציאה", "mpl": "מוציאים", "fpl": "מוציאות" },
      "past":    { "msg": "הוציא", "fsg": "הוציאה", "mpl": "הוציאו", "fpl": "הוציאו" },
      "future":  { "msg": "יוציא", "fsg": "תוציא", "mpl": "יוציאו", "fpl": "יוציאו" }
    }
  },
  {
    "id": "shvira_lev",
    "level": 2,
    "infinitive": "לשבור למישהו את הלב",
    "english": "to break someone's heart",
    "verb": "לשבור",
    "root": "ש.ב.ר",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "את הלב",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את הלב",
    "example": "אתה שובר לי את הלב",
    "negated": false,
    "literal_sg": "{s} breaks {p} heart",
    "literal_pl": "{s} break {p} heart",
    "literal_past": "{s} broke {p} heart",
    "literal_future": "{s} will break {p} heart",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "שובר", "fsg": "שוברת", "mpl": "שוברים", "fpl": "שוברות" },
      "past":    { "msg": "שבר", "fsg": "שברה", "mpl": "שברו", "fpl": "שברו" },
      "future":  { "msg": "ישבור", "fsg": "תשבור", "mpl": "ישברו", "fpl": "ישברו" }
    }
  },
  {
    "id": "asiya_hayim",
    "level": 2,
    "infinitive": "לעשות למישהו את החיים קשים",
    "english": "to make someone's life difficult",
    "verb": "לעשות",
    "root": "ע.ש.ה",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "את החיים קשים",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את החיים קשים",
    "example": "אתה עושה לי את החיים קשים",
    "negated": false,
    "literal_sg": "{s} makes {p} life difficult",
    "literal_pl": "{s} make {p} life difficult",
    "literal_past": "{s} made {p} life difficult",
    "literal_future": "{s} will make {p} life difficult",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "עושה", "fsg": "עושה", "mpl": "עושים", "fpl": "עושות" },
      "past":    { "msg": "עשה", "fsg": "עשתה", "mpl": "עשו", "fpl": "עשו" },
      "future":  { "msg": "יעשה", "fsg": "תעשה", "mpl": "יעשו", "fpl": "יעשו" }
    }
  },
  {
    "id": "hfalat_asiman",
    "level": 2,
    "infinitive": "להפיל למישהו את האסימון",
    "english": "to make it click/make sense for someone",
    "verb": "להפיל",
    "root": "נ.פ.ל",
    "binyan": "hifil",
    "object_type": "l_dative",
    "fixed_object": "את האסימון",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את האסימון",
    "example": "אתה מפיל לי את האסימון",
    "negated": false,
    "literal_sg": "{s} drops {p} token",
    "literal_pl": "{s} drop {p} token",
    "literal_past": "{s} dropped {p} token",
    "literal_future": "{s} will drop {p} token",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מפיל", "fsg": "מפילה", "mpl": "מפילים", "fpl": "מפילות" },
      "past":    { "msg": "הפיל", "fsg": "הפילה", "mpl": "הפילו", "fpl": "הפילו" },
      "future":  { "msg": "יפיל", "fsg": "תפיל", "mpl": "יפילו", "fpl": "יפילו" }
    }
  },
  {
    "id": "ptihat_einayim",
    "level": 2,
    "infinitive": "לפתוח למישהו את העיניים",
    "english": "to open someone's eyes",
    "verb": "לפתוח",
    "root": "פ.ת.ח",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "את העיניים",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את העיניים",
    "example": "אתה פותח לי את העיניים",
    "negated": false,
    "literal_sg": "{s} opens {p} eyes",
    "literal_pl": "{s} open {p} eyes",
    "literal_past": "{s} opened {p} eyes",
    "literal_future": "{s} will open {p} eyes",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "פותח", "fsg": "פותחת", "mpl": "פותחים", "fpl": "פותחות" },
      "past":    { "msg": "פתח", "fsg": "פתחה", "mpl": "פתחו", "fpl": "פתחו" },
      "future":  { "msg": "יפתח", "fsg": "תפתח", "mpl": "יפתחו", "fpl": "יפתחו" }
    },
    "conjugations_niqqud": {
      "present": { "msg": "פּוֹתֵחַ", "fsg": "פּוֹתַחַת", "mpl": "פּוֹתְחִים", "fpl": "פּוֹתְחוֹת" },
      "past":    { "msg": "פָּתַח", "fsg": "פָּתְחָה", "mpl": "פָּתְחוּ", "fpl": "פָּתְחוּ" },
      "future":  { "msg": "יִפְתַּח", "fsg": "תִּפְתַּח", "mpl": "יִפְתְּחוּ", "fpl": "יִפְתְּחוּ" }
    },
    "fixed_object_niqqud": "אֶת הָעֵינַיִם",
    "niqqud_status": "reviewed",
    "niqqud_sources": [
      "https://www.pealim.com/dict/1747-liftoach/",
      "https://terms.hebrew-academy.org.il/munnah/66449_1/%D7%A8%D6%B4%D7%A4%D6%B0%D7%A8%D7%95%D6%BC%D7%A3%20%D7%94%D6%B8%D7%A2%D6%B5%D7%99%D7%A0%D6%B7%D7%99%D6%B4%D7%9D"
    ]
  },
  {
    "id": "yeshiva_neshama",
    "level": 2,
    "infinitive": "לשבת למישהו על הנשמה",
    "english": "to suffocate / pressure someone",
    "verb": "לשבת",
    "root": "י.ש.ב",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "על הנשמה",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ על הנשמה",
    "example": "אתה יושב לי על הנשמה",
    "negated": false,
    "literal_sg": "{s} sits on {p} soul",
    "literal_pl": "{s} sit on {p} soul",
    "literal_past": "{s} sat on {p} soul",
    "literal_future": "{s} will sit on {p} soul",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "יושב", "fsg": "יושבת", "mpl": "יושבים", "fpl": "יושבות" },
      "past":    { "msg": "ישב", "fsg": "ישבה", "mpl": "ישבו", "fpl": "ישבו" },
      "future":  { "msg": "יישב", "fsg": "תישב", "mpl": "יישבו", "fpl": "יישבו" }
    }
  },
  {
    "id": "yerida_gav",
    "level": 2,
    "infinitive": "לרדת למישהו מהגב",
    "english": "to get off someone's back",
    "verb": "לרדת",
    "root": "י.ר.ד",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "מהגב",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ מהגב",
    "example": "אתה יורד לי מהגב",
    "negated": false,
    "literal_sg": "{s} gets off {p} back",
    "literal_pl": "{s} get off {p} back",
    "literal_past": "{s} got off {p} back",
    "literal_future": "{s} will get off {p} back",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "יורד", "fsg": "יורדת", "mpl": "יורדים", "fpl": "יורדות" },
      "past":    { "msg": "ירד", "fsg": "ירדה", "mpl": "ירדו", "fpl": "ירדו" },
      "future":  { "msg": "יירד", "fsg": "תירד", "mpl": "יירדו", "fpl": "יירדו" }
    }
  },
  {
    "id": "amida_derekh",
    "level": 2,
    "infinitive": "לעמוד למישהו בדרך",
    "english": "to stand in someone's way",
    "verb": "לעמוד",
    "root": "ע.מ.ד",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "בדרך",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ בדרך",
    "example": "אתה עומד לי בדרך",
    "negated": false,
    "literal_sg": "{s} stands in {p} way",
    "literal_pl": "{s} stand in {p} way",
    "literal_past": "{s} stood in {p} way",
    "literal_future": "{s} will stand in {p} way",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "עומד", "fsg": "עומדת", "mpl": "עומדים", "fpl": "עומדות" },
      "past":    { "msg": "עמד", "fsg": "עמדה", "mpl": "עמדו", "fpl": "עמדו" },
      "future":  { "msg": "יעמוד", "fsg": "תעמוד", "mpl": "יעמדו", "fpl": "יעמדו" }
    }
  },
  {
    "id": "khnisa_rosh",
    "level": 2,
    "infinitive": "להיכנס למישהו לראש",
    "english": "to get inside someone's head",
    "verb": "להיכנס",
    "root": "כ.נ.ס",
    "binyan": "nifal",
    "object_type": "l_dative",
    "fixed_object": "לראש",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ לראש",
    "example": "אתה נכנס לי לראש",
    "negated": false,
    "literal_sg": "{s} enters {p} head",
    "literal_pl": "{s} enter {p} head",
    "literal_past": "{s} entered {p} head",
    "literal_future": "{s} will enter {p} head",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "נכנס", "fsg": "נכנסת", "mpl": "נכנסים", "fpl": "נכנסות" },
      "past":    { "msg": "נכנס", "fsg": "נכנסה", "mpl": "נכנסו", "fpl": "נכנסו" },
      "future":  { "msg": "ייכנס", "fsg": "תיכנס", "mpl": "ייכנסו", "fpl": "ייכנסו" }
    }
  },
  {
    "id": "lo_yatza_rosh",
    "level": 2,
    "infinitive": "לא לצאת למישהו מהראש",
    "english": "to not leave someone's head",
    "verb": "לצאת",
    "root": "י.צ.א",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "מהראש",
    "template": "לא ⟨VERB⟩ ⟨L_OBJ⟩ מהראש",
    "example": "אתה לא יוצא לי מהראש",
    "negated": true,
    "literal_sg": "{s} doesn't leave {p} head",
    "literal_pl": "{s} don't leave {p} head",
    "literal_past": "{s} didn't leave {p} head",
    "literal_future": "{s} won't leave {p} head",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "יוצא", "fsg": "יוצאת", "mpl": "יוצאים", "fpl": "יוצאות" },
      "past":    { "msg": "יצא", "fsg": "יצאה", "mpl": "יצאו", "fpl": "יצאו" },
      "future":  { "msg": "ייצא", "fsg": "תצא", "mpl": "ייצאו", "fpl": "ייצאו" }
    }
  },
  {
    "id": "ntina_barosh",
    "level": 2,
    "infinitive": "לתת למישהו בראש",
    "english": "to tear into / yell at someone",
    "verb": "לתת",
    "root": "נ.ת.נ",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "בראש",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ בראש",
    "example": "אתה נותן לי בראש",
    "negated": false,
    "literal_sg": "{s} gives {o} in the head",
    "literal_pl": "{s} give {o} in the head",
    "literal_past": "{s} gave {o} in the head",
    "literal_future": "{s} will give {o} in the head",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "נותן", "fsg": "נותנת", "mpl": "נותנים", "fpl": "נותנות" },
      "past":    { "msg": "נתן", "fsg": "נתנה", "mpl": "נתנו", "fpl": "נתנו" },
      "future":  { "msg": "ייתן", "fsg": "תיתן", "mpl": "ייתנו", "fpl": "ייתנו" }
    }
  },
  {
    "id": "akhila_rosh",
    "level": 2,
    "infinitive": "לאכול למישהו את הראש",
    "english": "to nag / drive someone crazy with talk",
    "verb": "לאכול",
    "root": "א.כ.ל",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "את הראש",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את הראש",
    "example": "אתה אוכל לי את הראש",
    "negated": false,
    "literal_sg": "{s} eats {p} head",
    "literal_pl": "{s} eat {p} head",
    "literal_past": "{s} ate {p} head",
    "literal_future": "{s} will eat {p} head",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "אוכל", "fsg": "אוכלת", "mpl": "אוכלים", "fpl": "אוכלות" },
      "past":    { "msg": "אכל", "fsg": "אכלה", "mpl": "אכלו", "fpl": "אכלו" },
      "future":  { "msg": "יאכל", "fsg": "תאכל", "mpl": "יאכלו", "fpl": "יאכלו" }
    }
  },
  {
    "id": "gnivat_lev",
    "level": 2,
    "infinitive": "לגנוב למישהו את הלב",
    "english": "to steal someone's heart",
    "verb": "לגנוב",
    "root": "ג.נ.ב",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "את הלב",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את הלב",
    "example": "אתה גונב לי את הלב",
    "negated": false,
    "literal_sg": "{s} steals {p} heart",
    "literal_pl": "{s} steal {p} heart",
    "literal_past": "{s} stole {p} heart",
    "literal_future": "{s} will steal {p} heart",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "גונב", "fsg": "גונבת", "mpl": "גונבים", "fpl": "גונבות" },
      "past":    { "msg": "גנב", "fsg": "גנבה", "mpl": "גנבו", "fpl": "גנבו" },
      "future":  { "msg": "יגנוב", "fsg": "תגנוב", "mpl": "יגנבו", "fpl": "יגנבו" }
    }
  },
  {
    "id": "hotzaat_midato",
    "level": 3,
    "infinitive": "להוציא מישהו מדעתו",
    "english": "to drive someone out of their mind",
    "verb": "להוציא",
    "root": "י.צ.א",
    "binyan": "hifil",
    "object_type": "possessive_suffix",
    "suffix_noun": "דעת",
    "suffix_preposition": "מ",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩ ⟨SUFFIX_FORM⟩",
    "example": "אתה מוציא אותי מדעתי",
    "negated": false,
    "literal_sg": "{s} takes {o} out of {p} mind",
    "literal_pl": "{s} take {o} out of {p} mind",
    "literal_past": "{s} took {o} out of {p} mind",
    "literal_future": "{s} will take {o} out of {p} mind",
    "showMeaning": false,
    "suffix_forms": {
      "1sg": "מדעתי", "2msg": "מדעתך", "2fsg": "מדעתך",
      "3msg": "מדעתו", "3fsg": "מדעתה", "1pl": "מדעתנו",
      "2mpl": "מדעתכם", "2fpl": "מדעתכן", "3mpl": "מדעתם", "3fpl": "מדעתן"
    },
    "conjugations": {
      "present": { "msg": "מוציא", "fsg": "מוציאה", "mpl": "מוציאים", "fpl": "מוציאות" },
      "past":    { "msg": "הוציא", "fsg": "הוציאה", "mpl": "הוציאו", "fpl": "הוציאו" },
      "future":  { "msg": "יוציא", "fsg": "תוציא", "mpl": "יוציאו", "fpl": "יוציאו" }
    }
  },
  {
    "id": "hotzaat_miklav",
    "level": 3,
    "infinitive": "להוציא מישהו מכליו",
    "english": "to make someone totally lose it",
    "verb": "להוציא",
    "root": "י.צ.א",
    "binyan": "hifil",
    "object_type": "possessive_suffix",
    "suffix_noun": "כלים",
    "suffix_preposition": "מ",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩ ⟨SUFFIX_FORM⟩",
    "example": "אתה מוציא אותי מכליי",
    "negated": false,
    "literal_sg": "{s} takes {o} out of {p} vessels",
    "literal_pl": "{s} take {o} out of {p} vessels",
    "literal_past": "{s} took {o} out of {p} vessels",
    "literal_future": "{s} will take {o} out of {p} vessels",
    "showMeaning": true,
    "suffix_forms": {
      "1sg": "מכליי", "2msg": "מכליך", "2fsg": "מכליך",
      "3msg": "מכליו", "3fsg": "מכליה", "1pl": "מכלינו",
      "2mpl": "מכליכם", "2fpl": "מכליכן", "3mpl": "מכליהם", "3fpl": "מכליהן"
    },
    "conjugations": {
      "present": { "msg": "מוציא", "fsg": "מוציאה", "mpl": "מוציאים", "fpl": "מוציאות" },
      "past":    { "msg": "הוציא", "fsg": "הוציאה", "mpl": "הוציאו", "fpl": "הוציאו" },
      "future":  { "msg": "יוציא", "fsg": "תוציא", "mpl": "יוציאו", "fpl": "יוציאו" }
    }
  },
  {
    "id": "bilbul_moach",
    "level": 2,
    "infinitive": "לבלבל למישהו את המוח",
    "english": "to mess with someone's head / talk nonsense at someone",
    "verb": "לבלבל",
    "root": "ב.ל.ב.ל",
    "binyan": "piel",
    "object_type": "l_dative",
    "fixed_object": "את המוח",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את המוח",
    "example": "אתה מבלבל לי את המוח",
    "negated": false,
    "literal_sg": "{s} confuses {p} brain",
    "literal_pl": "{s} confuse {p} brain",
    "literal_past": "{s} confused {p} brain",
    "literal_future": "{s} will confuse {p} brain",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מבלבל", "fsg": "מבלבלת", "mpl": "מבלבלים", "fpl": "מבלבלות" },
      "past":    { "msg": "בלבל", "fsg": "בלבלה", "mpl": "בלבלו", "fpl": "בלבלו" },
      "future":  { "msg": "יבלבל", "fsg": "תבלבל", "mpl": "יבלבלו", "fpl": "יבלבלו" }
    }
  },
  {
    "id": "shtifat_moach",
    "level": 2,
    "infinitive": "לשטוף למישהו את המוח",
    "english": "to brainwash someone",
    "verb": "לשטוף",
    "root": "ש.ט.פ",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "את המוח",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את המוח",
    "example": "הפרסומות שוטפות לנו את המוח",
    "negated": false,
    "literal_sg": "{s} washes {p} brain",
    "literal_pl": "{s} wash {p} brain",
    "literal_past": "{s} washed {p} brain",
    "literal_future": "{s} will wash {p} brain",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "שוטף", "fsg": "שוטפת", "mpl": "שוטפים", "fpl": "שוטפות" },
      "past":    { "msg": "שטף", "fsg": "שטפה", "mpl": "שטפו", "fpl": "שטפו" },
      "future":  { "msg": "ישטוף", "fsg": "תשטוף", "mpl": "ישטפו", "fpl": "ישטפו" }
    }
  },
  {
    "id": "hotzaat_neshama",
    "level": 2,
    "infinitive": "להוציא למישהו את הנשמה",
    "english": "to wear someone down / drain someone completely",
    "verb": "להוציא",
    "root": "י.צ.א",
    "binyan": "hifil",
    "object_type": "l_dative",
    "fixed_object": "את הנשמה",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את הנשמה",
    "example": "אתה מוציא לי את הנשמה",
    "negated": false,
    "literal_sg": "{s} takes out {p} soul",
    "literal_pl": "{s} take out {p} soul",
    "literal_past": "{s} took out {p} soul",
    "literal_future": "{s} will take out {p} soul",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מוציא", "fsg": "מוציאה", "mpl": "מוציאים", "fpl": "מוציאות" },
      "past":    { "msg": "הוציא", "fsg": "הוציאה", "mpl": "הוציאו", "fpl": "הוציאו" },
      "future":  { "msg": "יוציא", "fsg": "תוציא", "mpl": "יוציאו", "fpl": "יוציאו" }
    }
  },
  {
    "id": "aliyat_atzabim",
    "level": 2,
    "infinitive": "לעלות למישהו על העצבים",
    "english": "to get on someone's nerves",
    "verb": "לעלות",
    "root": "ע.ל.ה",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "על העצבים",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ על העצבים",
    "example": "אתה עולה לי על העצבים",
    "negated": false,
    "literal_sg": "{s} climbs on {p} nerves",
    "literal_pl": "{s} climb on {p} nerves",
    "literal_past": "{s} climbed on {p} nerves",
    "literal_future": "{s} will climb on {p} nerves",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "עולה", "fsg": "עולה", "mpl": "עולים", "fpl": "עולות" },
      "past":    { "msg": "עלה", "fsg": "עלתה", "mpl": "עלו", "fpl": "עלו" },
      "future":  { "msg": "יעלה", "fsg": "תעלה", "mpl": "יעלו", "fpl": "יעלו" }
    }
  },
  {
    "id": "sivuv_rosh",
    "level": 2,
    "infinitive": "לסובב למישהו את הראש",
    "english": "to turn someone's head / sweet-talk someone",
    "verb": "לסובב",
    "root": "ס.ב.ב",
    "binyan": "piel",
    "object_type": "l_dative",
    "fixed_object": "את הראש",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את הראש",
    "example": "היא מסובבת לו את הראש",
    "negated": false,
    "literal_sg": "{s} spins {p} head",
    "literal_pl": "{s} spin {p} head",
    "literal_past": "{s} spun {p} head",
    "literal_future": "{s} will spin {p} head",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מסובב", "fsg": "מסובבת", "mpl": "מסובבים", "fpl": "מסובבות" },
      "past":    { "msg": "סובב", "fsg": "סובבה", "mpl": "סובבו", "fpl": "סובבו" },
      "future":  { "msg": "יסובב", "fsg": "תסובב", "mpl": "יסובבו", "fpl": "יסובבו" }
    }
  },
  {
    "id": "simat_regel",
    "level": 2,
    "infinitive": "לשים למישהו רגל",
    "english": "to trip someone up / sabotage someone",
    "verb": "לשים",
    "root": "ש.י.מ",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "רגל",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ רגל",
    "example": "הוא שם לי רגל",
    "negated": false,
    "literal_sg": "{s} puts a leg out for {o}",
    "literal_pl": "{s} put a leg out for {o}",
    "literal_past": "{s} put (past) a leg out for {o}",
    "literal_future": "{s} will put a leg out for {o}",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "שם", "fsg": "שמה", "mpl": "שמים", "fpl": "שמות" },
      "past":    { "msg": "שם", "fsg": "שמה", "mpl": "שמו", "fpl": "שמו" },
      "future":  { "msg": "ישים", "fsg": "תשים", "mpl": "ישימו", "fpl": "ישימו" }
    }
  },
  {
    "id": "chimum_lev",
    "level": 2,
    "infinitive": "לחמם למישהו את הלב",
    "english": "to warm someone's heart",
    "verb": "לחמם",
    "root": "ח.מ.מ",
    "binyan": "piel",
    "object_type": "l_dative",
    "fixed_object": "את הלב",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את הלב",
    "example": "אתה מחמם לי את הלב",
    "negated": false,
    "literal_sg": "{s} warms {p} heart",
    "literal_pl": "{s} warm {p} heart",
    "literal_past": "{s} warmed {p} heart",
    "literal_future": "{s} will warm {p} heart",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "מחמם", "fsg": "מחממת", "mpl": "מחממים", "fpl": "מחממות" },
      "past":    { "msg": "חימם", "fsg": "חיממה", "mpl": "חיממו", "fpl": "חיממו" },
      "future":  { "msg": "יחמם", "fsg": "תחמם", "mpl": "יחממו", "fpl": "יחממו" }
    }
  },
  {
    "id": "merihat_atzabim",
    "level": 3,
    "infinitive": "למרוט למישהו את העצבים",
    "english": "to fray someone's nerves / wear someone's patience thin",
    "verb": "למרוט",
    "root": "מ.ר.ט",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "את העצבים",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את העצבים",
    "example": "אתה מורט לי את העצבים",
    "negated": false,
    "literal_sg": "{s} plucks {p} nerves",
    "literal_pl": "{s} pluck {p} nerves",
    "literal_past": "{s} plucked {p} nerves",
    "literal_future": "{s} will pluck {p} nerves",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מורט", "fsg": "מורטת", "mpl": "מורטים", "fpl": "מורטות" },
      "past":    { "msg": "מרט", "fsg": "מרטה", "mpl": "מרטו", "fpl": "מרטו" },
      "future":  { "msg": "ימרוט", "fsg": "תמרוט", "mpl": "ימרטו", "fpl": "ימרטו" }
    }
  },
  {
    "id": "ruach_mifrasim",
    "level": 3,
    "infinitive": "להוציא למישהו את הרוח מהמפרשים",
    "english": "to take the wind out of someone's sails",
    "verb": "להוציא",
    "root": "י.צ.א",
    "binyan": "hifil",
    "object_type": "l_dative",
    "fixed_object": "את הרוח מהמפרשים",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את הרוח מהמפרשים",
    "example": "התשובה שלה הוציאה לו את הרוח מהמפרשים",
    "negated": false,
    "literal_sg": "{s} takes the wind out of {p} sails",
    "literal_pl": "{s} take the wind out of {p} sails",
    "literal_past": "{s} took the wind out of {p} sails",
    "literal_future": "{s} will take the wind out of {p} sails",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "מוציא", "fsg": "מוציאה", "mpl": "מוציאים", "fpl": "מוציאות" },
      "past":    { "msg": "הוציא", "fsg": "הוציאה", "mpl": "הוציאו", "fpl": "הוציאו" },
      "future":  { "msg": "יוציא", "fsg": "תוציא", "mpl": "יוציאו", "fpl": "יוציאו" }
    }
  },
  {
    "id": "sider",
    "level": 2,
    "infinitive": "לסדר מישהו",
    "english": "to screw someone over",
    "verb": "לסדר",
    "root": "ס.ד.ר",
    "binyan": "piel",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "הקבלן סידר אותנו",
    "negated": false,
    "literal_sg": "{s} screws {o} over",
    "literal_pl": "{s} screw {o} over",
    "literal_past": "{s} screwed {o} over",
    "literal_future": "{s} will screw {o} over",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "מסדר", "fsg": "מסדרת", "mpl": "מסדרים", "fpl": "מסדרות" },
      "past":    { "msg": "סידר", "fsg": "סידרה", "mpl": "סידרו", "fpl": "סידרו" },
      "future":  { "msg": "יסדר", "fsg": "תסדר", "mpl": "יסדרו", "fpl": "יסדרו" }
    },
    "conjugations_niqqud": {
      "present": { "msg": "מְסַדֵּר", "fsg": "מְסַדֶּרֶת", "mpl": "מְסַדְּרִים", "fpl": "מְסַדְּרוֹת" },
      "past":    { "msg": "סִדֵּר", "fsg": "סִדְּרָה", "mpl": "סִדְּרוּ", "fpl": "סִדְּרוּ" },
      "future":  { "msg": "יְסַדֵּר", "fsg": "תְּסַדֵּר", "mpl": "יְסַדְּרוּ", "fpl": "יְסַדְּרוּ" }
    },
    "niqqud_status": "reviewed",
    "niqqud_sources": ["https://www.pealim.com/dict/1320-lesader/"]
  },
  {
    "id": "marach",
    "level": 3,
    "infinitive": "למרוח מישהו",
    "english": "to string someone along",
    "verb": "למרוח",
    "root": "מ.ר.ח",
    "binyan": "paal",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "הוא מרח אותי שבועיים",
    "negated": false,
    "literal_sg": "{s} strings {o} along",
    "literal_pl": "{s} string {o} along",
    "literal_past": "{s} strung {o} along",
    "literal_future": "{s} will string {o} along",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "מורח", "fsg": "מורחת", "mpl": "מורחים", "fpl": "מורחות" },
      "past":    { "msg": "מרח", "fsg": "מרחה", "mpl": "מרחו", "fpl": "מרחו" },
      "future":  { "msg": "ימרח", "fsg": "תמרח", "mpl": "ימרחו", "fpl": "ימרחו" }
    }
  },
  {
    "id": "asiyat_yom",
    "level": 1,
    "infinitive": "לעשות למישהו את היום",
    "english": "to make someone's day",
    "verb": "לעשות",
    "root": "ע.ש.ה",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "את היום",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את היום",
    "example": "המחמאה שלך עשתה לי את היום",
    "negated": false,
    "literal_sg": "{s} makes {p} day",
    "literal_pl": "{s} make {p} day",
    "literal_past": "{s} made {p} day",
    "literal_future": "{s} will make {p} day",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "עושה", "fsg": "עושה", "mpl": "עושים", "fpl": "עושות" },
      "past":    { "msg": "עשה", "fsg": "עשתה", "mpl": "עשו", "fpl": "עשו" },
      "future":  { "msg": "יעשה", "fsg": "תעשה", "mpl": "יעשו", "fpl": "יעשו" }
    },
    "conjugations_niqqud": {
      "present": { "msg": "עוֹשֶׂה", "fsg": "עוֹשָׂה", "mpl": "עוֹשִׂים", "fpl": "עוֹשׂוֹת" },
      "past":    { "msg": "עָשָׂה", "fsg": "עָשְׂתָה", "mpl": "עָשׂוּ", "fpl": "עָשׂוּ" },
      "future":  { "msg": "יַעֲשֶׂה", "fsg": "תַּעֲשֶׂה", "mpl": "יַעֲשׂוּ", "fpl": "יַעֲשׂוּ" }
    },
    "fixed_object_niqqud": "אֶת הַיּוֹם",
    "niqqud_status": "reviewed",
    "niqqud_sources": [
      "https://www.pealim.com/dict/3-laasot/",
      "https://www.pealim.com/dict/5998-hayom/"
    ]
  },
  {
    "id": "haramat_moral",
    "level": 2,
    "infinitive": "להרים למישהו את המורל",
    "english": "to lift someone's spirits",
    "verb": "להרים",
    "root": "ר.ו.ם",
    "binyan": "hifil",
    "object_type": "l_dative",
    "fixed_object": "את המורל",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את המורל",
    "example": "השיר הזה מרים לי את המורל",
    "negated": false,
    "literal_sg": "{s} lifts {p} morale",
    "literal_pl": "{s} lift {p} morale",
    "literal_past": "{s} lifted {p} morale",
    "literal_future": "{s} will lift {p} morale",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מרים", "fsg": "מרימה", "mpl": "מרימים", "fpl": "מרימות" },
      "past":    { "msg": "הרים", "fsg": "הרימה", "mpl": "הרימו", "fpl": "הרימו" },
      "future":  { "msg": "ירים", "fsg": "תרים", "mpl": "ירימו", "fpl": "ירימו" }
    }
  },
  {
    "id": "harisat_matzav_ruach",
    "level": 2,
    "infinitive": "להרוס למישהו את מצב הרוח",
    "english": "to ruin someone's mood",
    "verb": "להרוס",
    "root": "ה.ר.ס",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "את מצב הרוח",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את מצב הרוח",
    "example": "החדשות הרסו לי את מצב הרוח",
    "negated": false,
    "literal_sg": "{s} ruins {p} mood",
    "literal_pl": "{s} ruin {p} mood",
    "literal_past": "{s} ruined {p} mood",
    "literal_future": "{s} will ruin {p} mood",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "הורס", "fsg": "הורסת", "mpl": "הורסים", "fpl": "הורסות" },
      "past":    { "msg": "הרס", "fsg": "הרסה", "mpl": "הרסו", "fpl": "הרסו" },
      "future":  { "msg": "יהרוס", "fsg": "תהרוס", "mpl": "יהרסו", "fpl": "יהרסו" }
    }
  },
  {
    "id": "gnivat_hatzaga",
    "level": 2,
    "infinitive": "לגנוב למישהו את ההצגה",
    "english": "to steal someone's thunder",
    "verb": "לגנוב",
    "root": "ג.נ.ב",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "את ההצגה",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את ההצגה",
    "example": "הוא גנב לי את ההצגה בישיבה",
    "negated": false,
    "literal_sg": "{s} steals {p} show",
    "literal_pl": "{s} steal {p} show",
    "literal_past": "{s} stole {p} show",
    "literal_future": "{s} will steal {p} show",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "גונב", "fsg": "גונבת", "mpl": "גונבים", "fpl": "גונבות" },
      "past":    { "msg": "גנב", "fsg": "גנבה", "mpl": "גנבו", "fpl": "גנבו" },
      "future":  { "msg": "יגנוב", "fsg": "תגנוב", "mpl": "יגנבו", "fpl": "יגנבו" }
    }
  },
  {
    "id": "drichat_yabalot",
    "level": 3,
    "infinitive": "לדרוך למישהו על היבלות",
    "english": "to touch a sore spot / hit a nerve",
    "verb": "לדרוך",
    "root": "ד.ר.כ",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "על היבלות",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ על היבלות",
    "example": "השאלה הזאת דרכה לי על היבלות",
    "negated": false,
    "literal_sg": "{s} steps on {p} blisters",
    "literal_pl": "{s} step on {p} blisters",
    "literal_past": "{s} stepped on {p} blisters",
    "literal_future": "{s} will step on {p} blisters",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "דורך", "fsg": "דורכת", "mpl": "דורכים", "fpl": "דורכות" },
      "past":    { "msg": "דרך", "fsg": "דרכה", "mpl": "דרכו", "fpl": "דרכו" },
      "future":  { "msg": "ידרוך", "fsg": "תדרוך", "mpl": "ידרכו", "fpl": "ידרכו" }
    }
  },
  {
    "id": "tsvitat_lev",
    "level": 2,
    "infinitive": "לצבוט למישהו בלב",
    "english": "to tug at someone's heartstrings",
    "verb": "לצבוט",
    "root": "צ.ב.ט",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "בלב",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ בלב",
    "example": "הסרט הזה צבט לי בלב",
    "negated": false,
    "literal_sg": "{s} pinches {p} heart",
    "literal_pl": "{s} pinch {p} heart",
    "literal_past": "{s} pinched {p} heart",
    "literal_future": "{s} will pinch {p} heart",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "צובט", "fsg": "צובטת", "mpl": "צובטים", "fpl": "צובטות" },
      "past":    { "msg": "צבט", "fsg": "צבטה", "mpl": "צבטו", "fpl": "צבטו" },
      "future":  { "msg": "יצבוט", "fsg": "תצבוט", "mpl": "יצבטו", "fpl": "יצבטו" }
    }
  },
  {
    "id": "hitzchik",
    "level": 1,
    "infinitive": "להצחיק מישהו",
    "english": "to crack someone up",
    "verb": "להצחיק",
    "root": "צ.ח.ק",
    "binyan": "hifil",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "הוא מצחיק אותי",
    "negated": false,
    "literal_sg": "{s} makes {o} laugh",
    "literal_pl": "{s} make {o} laugh",
    "literal_past": "{s} made {o} laugh",
    "literal_future": "{s} will make {o} laugh",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "מצחיק", "fsg": "מצחיקה", "mpl": "מצחיקים", "fpl": "מצחיקות" },
      "past":    { "msg": "הצחיק", "fsg": "הצחיקה", "mpl": "הצחיקו", "fpl": "הצחיקו" },
      "future":  { "msg": "יצחיק", "fsg": "תצחיק", "mpl": "יצחיקו", "fpl": "יצחיקו" }
    }
  },
  
  
  {
    "id": "bies",
    "level": 2,
    "infinitive": "לבאס מישהו",
    "english": "to bum someone out",
    "verb": "לבאס",
    "root": "ב.א.ס",
    "binyan": "piel",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "זה ממש מבאס אותי",
    "negated": false,
    "literal_sg": "{s} bums {o} out",
    "literal_pl": "{s} bum {o} out",
    "literal_past": "{s} bummed {o} out",
    "literal_future": "{s} will bum {o} out",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מבאס", "fsg": "מבאסת", "mpl": "מבאסים", "fpl": "מבאסות" },
      "past":    { "msg": "ביאס", "fsg": "ביאסה", "mpl": "ביאסו", "fpl": "ביאסו" },
      "future":  { "msg": "יבאס", "fsg": "תבאס", "mpl": "יבאסו", "fpl": "יבאסו" }
    }
  },
  
  
  
  
  
  
  {
    "id": "zarak",
    "level": 2,
    "infinitive": "לזרוק מישהו",
    "english": "to dump someone",
    "verb": "לזרוק",
    "root": "ז.ר.ק",
    "binyan": "paal",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "היא זרקה אותו אחרי שנה",
    "negated": false,
    "literal_sg": "{s} throws {o}",
    "literal_pl": "{s} throw {o}",
    "literal_past": "{s} threw {o}",
    "literal_future": "{s} will throw {o}",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "זורק", "fsg": "זורקת", "mpl": "זורקים", "fpl": "זורקות" },
      "past":    { "msg": "זרק", "fsg": "זרקה", "mpl": "זרקו", "fpl": "זרקו" },
      "future":  { "msg": "יזרוק", "fsg": "תזרוק", "mpl": "יזרקו", "fpl": "יזרקו" }
    }
  },
  {
    "id": "tafas_oti",
    "level": 2,
    "infinitive": "לתפוס מישהו",
    "english": "to catch someone out",
    "verb": "לתפוס",
    "root": "ת.פ.ס",
    "binyan": "paal",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "תפסת אותי",
    "negated": false,
    "literal_sg": "{s} catches {o}",
    "literal_pl": "{s} catch {o}",
    "literal_past": "{s} caught {o}",
    "literal_future": "{s} will catch {o}",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "תופס", "fsg": "תופסת", "mpl": "תופסים", "fpl": "תופסות" },
      "past":    { "msg": "תפס", "fsg": "תפסה", "mpl": "תפסו", "fpl": "תפסו" },
      "future":  { "msg": "יתפוס", "fsg": "תתפוס", "mpl": "יתפסו", "fpl": "יתפסו" }
    }
  },
  {
    "id": "dafak",
    "level": 3,
    "infinitive": "לדפוק מישהו",
    "english": "to screw someone over",
    "verb": "לדפוק",
    "root": "ד.פ.ק",
    "binyan": "paal",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "הם דפקו אותנו בחוזה",
    "negated": false,
    "literal_sg": "{s} knocks {o}",
    "literal_pl": "{s} knock {o}",
    "literal_past": "{s} knocked {o}",
    "literal_future": "{s} will knock {o}",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "דופק", "fsg": "דופקת", "mpl": "דופקים", "fpl": "דופקות" },
      "past":    { "msg": "דפק", "fsg": "דפקה", "mpl": "דפקו", "fpl": "דפקו" },
      "future":  { "msg": "ידפוק", "fsg": "תדפוק", "mpl": "ידפקו", "fpl": "ידפקו" }
    }
  },
  {
    "id": "heif",
    "level": 3,
    "infinitive": "להעיף מישהו",
    "english": "to boot someone out",
    "verb": "להעיף",
    "root": "ע.ו.פ",
    "binyan": "hifil",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "העיפו אותו מהעבודה",
    "negated": false,
    "literal_sg": "{s} flies {o} out",
    "literal_pl": "{s} fly {o} out",
    "literal_past": "{s} flew {o} out",
    "literal_future": "{s} will fly {o} out",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מעיף", "fsg": "מעיפה", "mpl": "מעיפים", "fpl": "מעיפות" },
      "past":    { "msg": "העיף", "fsg": "העיפה", "mpl": "העיפו", "fpl": "העיפו" },
      "future":  { "msg": "יעיף", "fsg": "תעיף", "mpl": "יעיפו", "fpl": "יעיפו" }
    }
  },
  
  
  
  
  
  
  
  {
    "id": "chisel",
    "level": 3,
    "infinitive": "לחסל מישהו",
    "english": "to finish someone off",
    "verb": "לחסל",
    "root": "ח.ס.ל",
    "binyan": "piel",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "האימון הזה חיסל אותי",
    "negated": false,
    "literal_sg": "{s} eliminates {o}",
    "literal_pl": "{s} eliminate {o}",
    "literal_past": "{s} eliminated {o}",
    "literal_future": "{s} will eliminate {o}",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מחסל", "fsg": "מחסלת", "mpl": "מחסלים", "fpl": "מחסלות" },
      "past":    { "msg": "חיסל", "fsg": "חיסלה", "mpl": "חיסלו", "fpl": "חיסלו" },
      "future":  { "msg": "יחסל", "fsg": "תחסל", "mpl": "יחסלו", "fpl": "יחסלו" }
    }
  },
  {
    "id": "hitish",
    "level": 3,
    "infinitive": "להתיש מישהו",
    "english": "to wear someone down",
    "verb": "להתיש",
    "root": "ת.ש.ש",
    "binyan": "hifil",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "הבירוקרטיה מתישה אותי",
    "negated": false,
    "literal_sg": "{s} wears {o} down",
    "literal_pl": "{s} wear {o} down",
    "literal_past": "{s} wore {o} down",
    "literal_future": "{s} will wear {o} down",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "מתיש", "fsg": "מתישה", "mpl": "מתישים", "fpl": "מתישות" },
      "past":    { "msg": "התיש", "fsg": "התישה", "mpl": "התישו", "fpl": "התישו" },
      "future":  { "msg": "יתיש", "fsg": "תתיש", "mpl": "יתישו", "fpl": "יתישו" }
    }
  },
  {
    "id": "rima",
    "level": 2,
    "infinitive": "לרמות מישהו",
    "english": "to cheat on someone",
    "verb": "לרמות",
    "root": "ר.מ.ה",
    "binyan": "piel",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "הוא רימה אותה",
    "negated": false,
    "literal_sg": "{s} deceives {o}",
    "literal_pl": "{s} deceive {o}",
    "literal_past": "{s} deceived {o}",
    "literal_future": "{s} will deceive {o}",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מרמה", "fsg": "מרמה", "mpl": "מרמים", "fpl": "מרמות" },
      "past":    { "msg": "רימה", "fsg": "רימתה", "mpl": "רימו", "fpl": "רימו" },
      "future":  { "msg": "ירמה", "fsg": "תרמה", "mpl": "ירמו", "fpl": "ירמו" }
    }
  },
  
  
  
  {
    "id": "nitzel",
    "level": 3,
    "infinitive": "לנצל מישהו",
    "english": "to take advantage of someone",
    "verb": "לנצל",
    "root": "נ.צ.ל",
    "binyan": "piel",
    "object_type": "direct",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩",
    "example": "הם ניצלו אותנו",
    "negated": false,
    "literal_sg": "{s} exploits {o}",
    "literal_pl": "{s} exploit {o}",
    "literal_past": "{s} exploited {o}",
    "literal_future": "{s} will exploit {o}",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מנצל", "fsg": "מנצלת", "mpl": "מנצלים", "fpl": "מנצלות" },
      "past":    { "msg": "ניצל", "fsg": "ניצלה", "mpl": "ניצלו", "fpl": "ניצלו" },
      "future":  { "msg": "ינצל", "fsg": "תנצל", "mpl": "ינצלו", "fpl": "ינצלו" }
    }
  },
  
  
  
  
  
  {
    "id": "asiyat_tova",
    "level": 1,
    "infinitive": "לעשות למישהו טובה",
    "english": "to do someone a favor",
    "verb": "לעשות",
    "root": "ע.ש.ה",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "טובה",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ טובה",
    "example": "תעשה לי טובה",
    "negated": false,
    "literal_sg": "{s} does {o} a favor",
    "literal_pl": "{s} do {o} a favor",
    "literal_past": "{s} did {o} a favor",
    "literal_future": "{s} will do {o} a favor",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "עושה", "fsg": "עושה", "mpl": "עושים", "fpl": "עושות" },
      "past":    { "msg": "עשה", "fsg": "עשתה", "mpl": "עשו", "fpl": "עשו" },
      "future":  { "msg": "יעשה", "fsg": "תעשה", "mpl": "יעשו", "fpl": "יעשו" }
    }
  },
  {
    "id": "dibur_al_halev",
    "level": 3,
    "infinitive": "לדבר למישהו על הלב",
    "english": "to talk someone round",
    "verb": "לדבר",
    "root": "ד.ב.ר",
    "binyan": "piel",
    "object_type": "l_dative",
    "fixed_object": "על הלב",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ על הלב",
    "example": "היא דיברה לי על הלב",
    "negated": false,
    "literal_sg": "{s} talks on {p} heart",
    "literal_pl": "{s} talk on {p} heart",
    "literal_past": "{s} talked on {p} heart",
    "literal_future": "{s} will talk on {p} heart",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מדבר", "fsg": "מדברת", "mpl": "מדברים", "fpl": "מדברות" },
      "past":    { "msg": "דיבר", "fsg": "דיברה", "mpl": "דיברו", "fpl": "דיברו" },
      "future":  { "msg": "ידבר", "fsg": "תדבר", "mpl": "ידברו", "fpl": "ידברו" }
    }
  },
  {
    "id": "asiyat_seder_barosh",
    "level": 3,
    "infinitive": "לעשות למישהו סדר בראש",
    "english": "to sort someone's head out",
    "verb": "לעשות",
    "root": "ע.ש.ה",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "סדר בראש",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ סדר בראש",
    "example": "השיחה עשתה לי סדר בראש",
    "negated": false,
    "literal_sg": "{s} makes order in {p} head",
    "literal_pl": "{s} make order in {p} head",
    "literal_past": "{s} made order in {p} head",
    "literal_future": "{s} will make order in {p} head",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "עושה", "fsg": "עושה", "mpl": "עושים", "fpl": "עושות" },
      "past":    { "msg": "עשה", "fsg": "עשתה", "mpl": "עשו", "fpl": "עשו" },
      "future":  { "msg": "יעשה", "fsg": "תעשה", "mpl": "יעשו", "fpl": "יעשו" }
    }
  },
  {
    "id": "hachzarat_chiyuch",
    "level": 2,
    "infinitive": "להחזיר למישהו את החיוך",
    "english": "to bring someone's smile back",
    "verb": "להחזיר",
    "root": "ח.ז.ר",
    "binyan": "hifil",
    "object_type": "l_dative",
    "fixed_object": "את החיוך",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את החיוך",
    "example": "הוא החזיר לי את החיוך",
    "negated": false,
    "literal_sg": "{s} returns {p} smile",
    "literal_pl": "{s} return {p} smile",
    "literal_past": "{s} returned {p} smile",
    "literal_future": "{s} will return {p} smile",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מחזיר", "fsg": "מחזירה", "mpl": "מחזירים", "fpl": "מחזירות" },
      "past":    { "msg": "החזיר", "fsg": "החזירה", "mpl": "החזירו", "fpl": "החזירו" },
      "future":  { "msg": "יחזיר", "fsg": "תחזיר", "mpl": "יחזירו", "fpl": "יחזירו" }
    }
  },
  {
    "id": "tfisat_ayin",
    "level": 2,
    "infinitive": "לתפוס למישהו את העין",
    "english": "to catch someone's eye",
    "verb": "לתפוס",
    "root": "ת.פ.ס",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "את העין",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את העין",
    "example": "השמלה תפסה לי את העין",
    "negated": false,
    "literal_sg": "{s} catches {p} eye",
    "literal_pl": "{s} catch {p} eye",
    "literal_past": "{s} caught {p} eye",
    "literal_future": "{s} will catch {p} eye",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "תופס", "fsg": "תופסת", "mpl": "תופסים", "fpl": "תופסות" },
      "past":    { "msg": "תפס", "fsg": "תפסה", "mpl": "תפסו", "fpl": "תפסו" },
      "future":  { "msg": "יתפוס", "fsg": "תתפוס", "mpl": "יתפסו", "fpl": "יתפסו" }
    }
  },
  {
    "id": "chisachon_keev",
    "level": 2,
    "infinitive": "לחסוך למישהו את הכאב",
    "english": "to spare someone the pain",
    "verb": "לחסוך",
    "root": "ח.ס.כ",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "את הכאב",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את הכאב",
    "example": "חסכת לי את הכאב",
    "negated": false,
    "literal_sg": "{s} saves {o} the pain",
    "literal_pl": "{s} save {o} the pain",
    "literal_past": "{s} saved {o} the pain",
    "literal_future": "{s} will save {o} the pain",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "חוסך", "fsg": "חוסכת", "mpl": "חוסכים", "fpl": "חוסכות" },
      "past":    { "msg": "חסך", "fsg": "חסכה", "mpl": "חסכו", "fpl": "חסכו" },
      "future":  { "msg": "יחסוך", "fsg": "תחסוך", "mpl": "יחסכו", "fpl": "יחסכו" }
    }
  },
  {
    "id": "haarat_yom",
    "level": 2,
    "infinitive": "להאיר למישהו את היום",
    "english": "to make someone's day",
    "verb": "להאיר",
    "root": "א.ו.ר",
    "binyan": "hifil",
    "object_type": "l_dative",
    "fixed_object": "את היום",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את היום",
    "example": "ההודעה שלך האירה לי את היום",
    "negated": false,
    "literal_sg": "{s} lights up {p} day",
    "literal_pl": "{s} light up {p} day",
    "literal_past": "{s} lit up {p} day",
    "literal_future": "{s} will light up {p} day",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מאיר", "fsg": "מאירה", "mpl": "מאירים", "fpl": "מאירות" },
      "past":    { "msg": "האיר", "fsg": "האירה", "mpl": "האירו", "fpl": "האירו" },
      "future":  { "msg": "יאיר", "fsg": "תאיר", "mpl": "יאירו", "fpl": "יאירו" }
    }
  },
  {
    "id": "mirur_chayim",
    "level": 3,
    "infinitive": "למרר למישהו את החיים",
    "english": "to make someone's life miserable",
    "verb": "למרר",
    "root": "מ.ר.ר",
    "binyan": "piel",
    "object_type": "l_dative",
    "fixed_object": "את החיים",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את החיים",
    "example": "השכן ממרר לנו את החיים",
    "negated": false,
    "literal_sg": "{s} embitters {p} life",
    "literal_pl": "{s} embitter {p} life",
    "literal_past": "{s} embittered {p} life",
    "literal_future": "{s} will embitter {p} life",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "ממרר", "fsg": "ממררת", "mpl": "ממררים", "fpl": "ממררות" },
      "past":    { "msg": "מירר", "fsg": "מיררה", "mpl": "מיררו", "fpl": "מיררו" },
      "future":  { "msg": "ימרר", "fsg": "תמרר", "mpl": "ימררו", "fpl": "ימררו" }
    }
  },
  {
    "id": "asiyat_mavet",
    "level": 3,
    "infinitive": "לעשות למישהו את המוות",
    "english": "to give someone hell",
    "verb": "לעשות",
    "root": "ע.ש.ה",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "את המוות",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את המוות",
    "example": "הם עשו לי את המוות",
    "negated": false,
    "literal_sg": "{s} makes {p} death",
    "literal_pl": "{s} make {p} death",
    "literal_past": "{s} made {p} death",
    "literal_future": "{s} will make {p} death",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "עושה", "fsg": "עושה", "mpl": "עושים", "fpl": "עושות" },
      "past":    { "msg": "עשה", "fsg": "עשתה", "mpl": "עשו", "fpl": "עשו" },
      "future":  { "msg": "יעשה", "fsg": "תעשה", "mpl": "יעשו", "fpl": "יעשו" }
    }
  },
  {
    "id": "haramat_telefon",
    "level": 2,
    "infinitive": "להרים למישהו טלפון",
    "english": "to give someone a call",
    "verb": "להרים",
    "root": "ר.ו.מ",
    "binyan": "hifil",
    "object_type": "l_dative",
    "fixed_object": "טלפון",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ טלפון",
    "example": "תרים לי טלפון בערב",
    "negated": false,
    "literal_sg": "{s} lifts a phone for {o}",
    "literal_pl": "{s} lift a phone for {o}",
    "literal_past": "{s} lifted a phone for {o}",
    "literal_future": "{s} will lift a phone for {o}",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מרים", "fsg": "מרימה", "mpl": "מרימים", "fpl": "מרימות" },
      "past":    { "msg": "הרים", "fsg": "הרימה", "mpl": "הרימו", "fpl": "הרימו" },
      "future":  { "msg": "ירים", "fsg": "תרים", "mpl": "ירימו", "fpl": "ירימו" }
    }
  },
  {
    "id": "ntinat_kavod",
    "level": 1,
    "infinitive": "לתת למישהו כבוד",
    "english": "to show someone respect",
    "verb": "לתת",
    "root": "נ.ת.נ",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "כבוד",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ כבוד",
    "example": "תן לה כבוד",
    "negated": false,
    "literal_sg": "{s} gives {o} respect",
    "literal_pl": "{s} give {o} respect",
    "literal_past": "{s} gave {o} respect",
    "literal_future": "{s} will give {o} respect",
    "showMeaning": false,
    "conjugations": {
      "present": { "msg": "נותן", "fsg": "נותנת", "mpl": "נותנים", "fpl": "נותנות" },
      "past":    { "msg": "נתן", "fsg": "נתנה", "mpl": "נתנו", "fpl": "נתנו" },
      "future":  { "msg": "ייתן", "fsg": "תיתן", "mpl": "ייתנו", "fpl": "ייתנו" }
    }
  },
  {
    "id": "shibush_tochniyot",
    "level": 3,
    "infinitive": "לשבש למישהו את התוכניות",
    "english": "to mess up someone's plans",
    "verb": "לשבש",
    "root": "ש.ב.ש",
    "binyan": "piel",
    "object_type": "l_dative",
    "fixed_object": "את התוכניות",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את התוכניות",
    "example": "הגשם שיבש לנו את התוכניות",
    "negated": false,
    "literal_sg": "{s} disrupts {p} plans",
    "literal_pl": "{s} disrupt {p} plans",
    "literal_past": "{s} disrupted {p} plans",
    "literal_future": "{s} will disrupt {p} plans",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "משבש", "fsg": "משבשת", "mpl": "משבשים", "fpl": "משבשות" },
      "past":    { "msg": "שיבש", "fsg": "שיבשה", "mpl": "שיבשו", "fpl": "שיבשו" },
      "future":  { "msg": "ישבש", "fsg": "תשבש", "mpl": "ישבשו", "fpl": "ישבשו" }
    }
  },
  {
    "id": "zriyat_melach",
    "level": 4,
    "infinitive": "לזרות למישהו מלח על הפצעים",
    "english": "to rub salt in someone's wounds",
    "verb": "לזרות",
    "root": "ז.ר.ה",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "מלח על הפצעים",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ מלח על הפצעים",
    "example": "אל תזרה לי מלח על הפצעים",
    "negated": false,
    "literal_sg": "{s} scatters salt on {p} wounds",
    "literal_pl": "{s} scatter salt on {p} wounds",
    "literal_past": "{s} scattered salt on {p} wounds",
    "literal_future": "{s} will scatter salt on {p} wounds",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "זורה", "fsg": "זורה", "mpl": "זורים", "fpl": "זורות" },
      "past":    { "msg": "זרה", "fsg": "זרתה", "mpl": "זרו", "fpl": "זרו" },
      "future":  { "msg": "יזרה", "fsg": "תזרה", "mpl": "יזרו", "fpl": "יזרו" }
    }
  },
  {
    "id": "hotzaat_milim",
    "level": 4,
    "infinitive": "להוציא למישהו את המילים מהפה",
    "english": "to take the words out of someone's mouth",
    "verb": "להוציא",
    "root": "י.צ.א",
    "binyan": "hifil",
    "object_type": "l_dative",
    "fixed_object": "את המילים מהפה",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את המילים מהפה",
    "example": "הוצאת לי את המילים מהפה",
    "negated": false,
    "literal_sg": "{s} takes the words out of {p} mouth",
    "literal_pl": "{s} take the words out of {p} mouth",
    "literal_past": "{s} took the words out of {p} mouth",
    "literal_future": "{s} will take the words out of {p} mouth",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מוציא", "fsg": "מוציאה", "mpl": "מוציאים", "fpl": "מוציאות" },
      "past":    { "msg": "הוציא", "fsg": "הוציאה", "mpl": "הוציאו", "fpl": "הוציאו" },
      "future":  { "msg": "יוציא", "fsg": "תוציא", "mpl": "יוציאו", "fpl": "יוציאו" }
    }
  },
  {
    "id": "sgirat_pina",
    "level": 3,
    "infinitive": "לסגור למישהו פינה",
    "english": "to sort something out for someone",
    "verb": "לסגור",
    "root": "ס.ג.ר",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "פינה",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ פינה",
    "example": "הוא סגר לי פינה מול הבנק",
    "negated": false,
    "literal_sg": "{s} closes {o} a corner",
    "literal_pl": "{s} close {o} a corner",
    "literal_past": "{s} closed {o} a corner",
    "literal_future": "{s} will close {o} a corner",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "סוגר", "fsg": "סוגרת", "mpl": "סוגרים", "fpl": "סוגרות" },
      "past":    { "msg": "סגר", "fsg": "סגרה", "mpl": "סגרו", "fpl": "סגרו" },
      "future":  { "msg": "יסגור", "fsg": "תסגור", "mpl": "יסגרו", "fpl": "יסגרו" }
    }
  },
  {
    "id": "ptichat_delet",
    "level": 2,
    "infinitive": "לפתוח למישהו דלת",
    "english": "to open a door for someone",
    "verb": "לפתוח",
    "root": "פ.ת.ח",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "דלת",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ דלת",
    "example": "הקורס פתח לי דלת",
    "negated": false,
    "literal_sg": "{s} opens {o} a door",
    "literal_pl": "{s} open {o} a door",
    "literal_past": "{s} opened {o} a door",
    "literal_future": "{s} will open {o} a door",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "פותח", "fsg": "פותחת", "mpl": "פותחים", "fpl": "פותחות" },
      "past":    { "msg": "פתח", "fsg": "פתחה", "mpl": "פתחו", "fpl": "פתחו" },
      "future":  { "msg": "יפתח", "fsg": "תפתח", "mpl": "יפתחו", "fpl": "יפתחו" }
    }
  },
  {
    "id": "hatayat_ozen",
    "level": 4,
    "infinitive": "להטות למישהו אוזן",
    "english": "to lend someone an ear",
    "verb": "להטות",
    "root": "נ.ט.ה",
    "binyan": "hifil",
    "object_type": "l_dative",
    "fixed_object": "אוזן",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ אוזן",
    "example": "הוא הטה לי אוזן",
    "negated": false,
    "literal_sg": "{s} inclines an ear to {o}",
    "literal_pl": "{s} incline an ear to {o}",
    "literal_past": "{s} inclined an ear to {o}",
    "literal_future": "{s} will incline an ear to {o}",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "מטה", "fsg": "מטה", "mpl": "מטים", "fpl": "מטות" },
      "past":    { "msg": "הטה", "fsg": "הטתה", "mpl": "הטו", "fpl": "הטו" },
      "future":  { "msg": "יטה", "fsg": "תטה", "mpl": "יטו", "fpl": "יטו" }
    }
  },
  {
    "id": "hafichat_chayim",
    "level": 3,
    "infinitive": "להפוך למישהו את החיים",
    "english": "to turn someone's life upside down",
    "verb": "להפוך",
    "root": "ה.פ.כ",
    "binyan": "paal",
    "object_type": "l_dative",
    "fixed_object": "את החיים",
    "template": "⟨VERB⟩ ⟨L_OBJ⟩ את החיים",
    "example": "המעבר הפך לנו את החיים",
    "negated": false,
    "literal_sg": "{s} turns {p} life over",
    "literal_pl": "{s} turn {p} life over",
    "literal_past": "{s} turned {p} life over",
    "literal_future": "{s} will turn {p} life over",
    "showMeaning": true,
    "conjugations": {
      "present": { "msg": "הופך", "fsg": "הופכת", "mpl": "הופכים", "fpl": "הופכות" },
      "past":    { "msg": "הפך", "fsg": "הפכה", "mpl": "הפכו", "fpl": "הפכו" },
      "future":  { "msg": "יהפוך", "fsg": "תהפוך", "mpl": "יהפכו", "fpl": "יהפכו" }
    }
  },
  {
    "id": "hotzaa_mishalva",
    "level": 3,
    "infinitive": "להוציא מישהו משלוותו",
    "english": "to throw someone off balance",
    "verb": "להוציא",
    "root": "י.צ.א",
    "binyan": "hifil",
    "object_type": "possessive_suffix",
    "suffix_noun": "שלווה",
    "suffix_preposition": "מ",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩ ⟨SUFFIX_FORM⟩",
    "example": "הידיעה הוציאה אותי משלוותי",
    "negated": false,
    "literal_sg": "{s} takes {o} out of {p} calm",
    "literal_pl": "{s} take {o} out of {p} calm",
    "literal_past": "{s} took {o} out of {p} calm",
    "literal_future": "{s} will take {o} out of {p} calm",
    "showMeaning": true,
    "suffix_forms": {
      "1sg": "משלוותי",
      "2msg": "משלוותך",
      "2fsg": "משלוותך",
      "3msg": "משלוותו",
      "3fsg": "משלוותה",
      "1pl": "משלוותנו",
      "2mpl": "משלוותכם",
      "2fpl": "משלוותכן",
      "3mpl": "משלוותם",
      "3fpl": "משלוותן"
    },
    "conjugations": {
      "present": { "msg": "מוציא", "fsg": "מוציאה", "mpl": "מוציאים", "fpl": "מוציאות" },
      "past":    { "msg": "הוציא", "fsg": "הוציאה", "mpl": "הוציאו", "fpl": "הוציאו" },
      "future":  { "msg": "יוציא", "fsg": "תוציא", "mpl": "יוציאו", "fpl": "יוציאו" }
    }
  },
  {
    "id": "haamada_bimkomo",
    "level": 3,
    "infinitive": "להעמיד מישהו במקומו",
    "english": "to put someone in their place",
    "verb": "להעמיד",
    "root": "ע.מ.ד",
    "binyan": "hifil",
    "object_type": "possessive_suffix",
    "suffix_noun": "מקום",
    "suffix_preposition": "ב",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩ ⟨SUFFIX_FORM⟩",
    "example": "היא העמידה אותו במקומו",
    "negated": false,
    "literal_sg": "{s} stands {o} in {p} place",
    "literal_pl": "{s} stand {o} in {p} place",
    "literal_past": "{s} stood {o} in {p} place",
    "literal_future": "{s} will stand {o} in {p} place",
    "showMeaning": true,
    "suffix_forms": {
      "1sg": "במקומי",
      "2msg": "במקומך",
      "2fsg": "במקומך",
      "3msg": "במקומו",
      "3fsg": "במקומה",
      "1pl": "במקומנו",
      "2mpl": "במקומכם",
      "2fpl": "במקומכן",
      "3mpl": "במקומם",
      "3fpl": "במקומן"
    },
    "conjugations": {
      "present": { "msg": "מעמיד", "fsg": "מעמידה", "mpl": "מעמידים", "fpl": "מעמידות" },
      "past":    { "msg": "העמיד", "fsg": "העמידה", "mpl": "העמידו", "fpl": "העמידו" },
      "future":  { "msg": "יעמיד", "fsg": "תעמיד", "mpl": "יעמידו", "fpl": "יעמידו" }
    }
  },
  {
    "id": "tfisa_bimilato",
    "level": 4,
    "infinitive": "לתפוס מישהו במילתו",
    "english": "to take someone at their word",
    "verb": "לתפוס",
    "root": "ת.פ.ס",
    "binyan": "paal",
    "object_type": "possessive_suffix",
    "suffix_noun": "מילה",
    "suffix_preposition": "ב",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩ ⟨SUFFIX_FORM⟩",
    "example": "תפסתי אותו במילתו",
    "negated": false,
    "literal_sg": "{s} catches {o} at {p} word",
    "literal_pl": "{s} catch {o} at {p} word",
    "literal_past": "{s} caught {o} at {p} word",
    "literal_future": "{s} will catch {o} at {p} word",
    "showMeaning": true,
    "suffix_forms": {
      "1sg": "במילתי",
      "2msg": "במילתך",
      "2fsg": "במילתך",
      "3msg": "במילתו",
      "3fsg": "במילתה",
      "1pl": "במילתנו",
      "2mpl": "במילתכם",
      "2fpl": "במילתכן",
      "3mpl": "במילתם",
      "3fpl": "במילתן"
    },
    "conjugations": {
      "present": { "msg": "תופס", "fsg": "תופסת", "mpl": "תופסים", "fpl": "תופסות" },
      "past":    { "msg": "תפס", "fsg": "תפסה", "mpl": "תפסו", "fpl": "תפסו" },
      "future":  { "msg": "יתפוס", "fsg": "תתפוס", "mpl": "יתפסו", "fpl": "יתפסו" }
    }
  },
  {
    "id": "hachzara_leatzmo",
    "level": 3,
    "infinitive": "להחזיר מישהו לעצמו",
    "english": "to bring someone back to themselves",
    "verb": "להחזיר",
    "root": "ח.ז.ר",
    "binyan": "hifil",
    "object_type": "possessive_suffix",
    "suffix_noun": "עצם",
    "suffix_preposition": "ל",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩ ⟨SUFFIX_FORM⟩",
    "example": "החופשה החזירה אותי לעצמי",
    "negated": false,
    "literal_sg": "{s} brings {o} back to {p} self",
    "literal_pl": "{s} bring {o} back to {p} self",
    "literal_past": "{s} brought {o} back to {p} self",
    "literal_future": "{s} will bring {o} back to {p} self",
    "showMeaning": true,
    "suffix_forms": {
      "1sg": "לעצמי",
      "2msg": "לעצמך",
      "2fsg": "לעצמך",
      "3msg": "לעצמו",
      "3fsg": "לעצמה",
      "1pl": "לעצמנו",
      "2mpl": "לעצמכם",
      "2fpl": "לעצמכן",
      "3mpl": "לעצמם",
      "3fpl": "לעצמן"
    },
    "conjugations": {
      "present": { "msg": "מחזיר", "fsg": "מחזירה", "mpl": "מחזירים", "fpl": "מחזירות" },
      "past":    { "msg": "החזיר", "fsg": "החזירה", "mpl": "החזירו", "fpl": "החזירו" },
      "future":  { "msg": "יחזיר", "fsg": "תחזיר", "mpl": "יחזירו", "fpl": "יחזירו" }
    },
    "conjugations_niqqud": {
      "present": { "msg": "מַחְזִיר", "fsg": "מַחְזִירָה", "mpl": "מַחְזִירִים", "fpl": "מַחְזִירוֹת" },
      "past":    { "msg": "הֶחְזִיר", "fsg": "הֶחְזִירָה", "mpl": "הֶחְזִירוּ", "fpl": "הֶחְזִירוּ" },
      "future":  { "msg": "יַחְזִיר", "fsg": "תַּחְזִיר", "mpl": "יַחְזִירוּ", "fpl": "יַחְזִירוּ" }
    },
    "suffix_forms_niqqud": {
      "1sg": "לְעַצְמִי",
      "2msg": "לְעַצְמְךָ",
      "2fsg": "לְעַצְמֵךְ",
      "3msg": "לְעַצְמוֹ",
      "3fsg": "לְעַצְמָהּ",
      "1pl": "לְעַצְמֵנוּ",
      "2mpl": "לְעַצְמְכֶם",
      "2fpl": "לְעַצְמְכֶן",
      "3mpl": "לְעַצְמָם",
      "3fpl": "לְעַצְמָן"
    },
    "niqqud_status": "reviewed",
    "niqqud_sources": [
      "https://www.pealim.com/dict/581-lehachazir/",
      "https://hebrew-academy.org.il/%D7%A0%D7%98%D7%99%D7%99%D7%AA-%D7%9E%D7%99%D7%9C%D7%95%D7%AA-%D7%94%D7%99%D7%97%D7%A1/"
    ]
  },
  {
    "id": "haavara_al_daato",
    "level": 4,
    "infinitive": "להעביר מישהו על דעתו",
    "english": "to drive someone out of their mind",
    "verb": "להעביר",
    "root": "ע.ב.ר",
    "binyan": "hifil",
    "object_type": "possessive_suffix",
    "suffix_noun": "דעת",
    "suffix_preposition": "על",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩ ⟨SUFFIX_FORM⟩",
    "example": "הרעש מעביר אותי על דעתי",
    "negated": false,
    "literal_sg": "{s} drives {o} past {p} senses",
    "literal_pl": "{s} drive {o} past {p} senses",
    "literal_past": "{s} drove {o} past {p} senses",
    "literal_future": "{s} will drive {o} past {p} senses",
    "showMeaning": true,
    "suffix_forms": {
      "1sg": "על דעתי",
      "2msg": "על דעתך",
      "2fsg": "על דעתך",
      "3msg": "על דעתו",
      "3fsg": "על דעתה",
      "1pl": "על דעתנו",
      "2mpl": "על דעתכם",
      "2fpl": "על דעתכן",
      "3mpl": "על דעתם",
      "3fpl": "על דעתן"
    },
    "conjugations": {
      "present": { "msg": "מעביר", "fsg": "מעבירה", "mpl": "מעבירים", "fpl": "מעבירות" },
      "past":    { "msg": "העביר", "fsg": "העבירה", "mpl": "העבירו", "fpl": "העבירו" },
      "future":  { "msg": "יעביר", "fsg": "תעביר", "mpl": "יעבירו", "fpl": "יעבירו" }
    }
  },
  {
    "id": "hashara_betzarato",
    "level": 4,
    "infinitive": "להשאיר מישהו בצרתו",
    "english": "to leave someone in the lurch",
    "verb": "להשאיר",
    "root": "ש.א.ר",
    "binyan": "hifil",
    "object_type": "possessive_suffix",
    "suffix_noun": "צרה",
    "suffix_preposition": "ב",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩ ⟨SUFFIX_FORM⟩",
    "example": "הם השאירו אותנו בצרתנו",
    "negated": false,
    "literal_sg": "{s} leaves {o} in {p} trouble",
    "literal_pl": "{s} leave {o} in {p} trouble",
    "literal_past": "{s} left {o} in {p} trouble",
    "literal_future": "{s} will leave {o} in {p} trouble",
    "showMeaning": true,
    "suffix_forms": {
      "1sg": "בצרתי",
      "2msg": "בצרתך",
      "2fsg": "בצרתך",
      "3msg": "בצרתו",
      "3fsg": "בצרתה",
      "1pl": "בצרתנו",
      "2mpl": "בצרתכם",
      "2fpl": "בצרתכן",
      "3mpl": "בצרתם",
      "3fpl": "בצרתן"
    },
    "conjugations": {
      "present": { "msg": "משאיר", "fsg": "משאירה", "mpl": "משאירים", "fpl": "משאירות" },
      "past":    { "msg": "השאיר", "fsg": "השאירה", "mpl": "השאירו", "fpl": "השאירו" },
      "future":  { "msg": "ישאיר", "fsg": "תשאיר", "mpl": "ישאירו", "fpl": "ישאירו" }
    }
  },
  {
    "id": "haamada_al_tauto",
    "level": 4,
    "infinitive": "להעמיד מישהו על טעותו",
    "english": "to set someone straight",
    "verb": "להעמיד",
    "root": "ע.מ.ד",
    "binyan": "hifil",
    "object_type": "possessive_suffix",
    "suffix_noun": "טעות",
    "suffix_preposition": "על",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩ ⟨SUFFIX_FORM⟩",
    "example": "המורה העמידה אותי על טעותי",
    "negated": false,
    "literal_sg": "{s} sets {o} straight about {p} mistake",
    "literal_pl": "{s} set {o} straight about {p} mistake",
    "literal_past": "{s} set {o} straight about {p} mistake",
    "literal_future": "{s} will set {o} straight about {p} mistake",
    "showMeaning": true,
    "suffix_forms": {
      "1sg": "על טעותי",
      "2msg": "על טעותך",
      "2fsg": "על טעותך",
      "3msg": "על טעותו",
      "3fsg": "על טעותה",
      "1pl": "על טעותנו",
      "2mpl": "על טעותכם",
      "2fpl": "על טעותכן",
      "3mpl": "על טעותם",
      "3fpl": "על טעותן"
    },
    "conjugations": {
      "present": { "msg": "מעמיד", "fsg": "מעמידה", "mpl": "מעמידים", "fpl": "מעמידות" },
      "past":    { "msg": "העמיד", "fsg": "העמידה", "mpl": "העמידו", "fpl": "העמידו" },
      "future":  { "msg": "יעמיד", "fsg": "תעמיד", "mpl": "יעמידו", "fpl": "יעמידו" }
    }
  },
  {
    "id": "tfisa_bekilkelato",
    "level": 4,
    "infinitive": "לתפוס מישהו בקלקלתו",
    "english": "to catch someone red-handed",
    "verb": "לתפוס",
    "root": "ת.פ.ס",
    "binyan": "paal",
    "object_type": "possessive_suffix",
    "suffix_noun": "קלקלה",
    "suffix_preposition": "ב",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩ ⟨SUFFIX_FORM⟩",
    "example": "תפסו אותו בקלקלתו",
    "negated": false,
    "literal_sg": "{s} catches {o} in {p} wrongdoing",
    "literal_pl": "{s} catch {o} in {p} wrongdoing",
    "literal_past": "{s} caught {o} in {p} wrongdoing",
    "literal_future": "{s} will catch {o} in {p} wrongdoing",
    "showMeaning": true,
    "suffix_forms": {
      "1sg": "בקלקלתי",
      "2msg": "בקלקלתך",
      "2fsg": "בקלקלתך",
      "3msg": "בקלקלתו",
      "3fsg": "בקלקלתה",
      "1pl": "בקלקלתנו",
      "2mpl": "בקלקלתכם",
      "2fpl": "בקלקלתכן",
      "3mpl": "בקלקלתם",
      "3fpl": "בקלקלתן"
    },
    "conjugations": {
      "present": { "msg": "תופס", "fsg": "תופסת", "mpl": "תופסים", "fpl": "תופסות" },
      "past":    { "msg": "תפס", "fsg": "תפסה", "mpl": "תפסו", "fpl": "תפסו" },
      "future":  { "msg": "יתפוס", "fsg": "תתפוס", "mpl": "יתפסו", "fpl": "יתפסו" }
    }
  },
  {
    "id": "ktia_bidvarav",
    "level": 3,
    "infinitive": "לקטוע מישהו בדבריו",
    "english": "to cut someone off mid-sentence",
    "verb": "לקטוע",
    "root": "ק.ט.ע",
    "binyan": "paal",
    "object_type": "possessive_suffix",
    "suffix_noun": "דברים",
    "suffix_preposition": "ב",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩ ⟨SUFFIX_FORM⟩",
    "example": "הוא קטע אותי בדבריי",
    "negated": false,
    "literal_sg": "{s} cuts {o} off in {p} words",
    "literal_pl": "{s} cut {o} off in {p} words",
    "literal_past": "{s} cut {o} off in {p} words",
    "literal_future": "{s} will cut {o} off in {p} words",
    "showMeaning": true,
    "suffix_forms": {
      "1sg": "בדבריי",
      "2msg": "בדבריך",
      "2fsg": "בדבריך",
      "3msg": "בדבריו",
      "3fsg": "בדבריה",
      "1pl": "בדברינו",
      "2mpl": "בדבריכם",
      "2fpl": "בדבריכן",
      "3mpl": "בדבריהם",
      "3fpl": "בדבריהן"
    },
    "conjugations": {
      "present": { "msg": "קוטע", "fsg": "קוטעת", "mpl": "קוטעים", "fpl": "קוטעות" },
      "past":    { "msg": "קטע", "fsg": "קטעה", "mpl": "קטעו", "fpl": "קטעו" },
      "future":  { "msg": "יקטע", "fsg": "תקטע", "mpl": "יקטעו", "fpl": "יקטעו" }
    }
  },
  {
    "id": "chizuk_bedaato",
    "level": 3,
    "infinitive": "לחזק מישהו בדעתו",
    "english": "to reinforce someone's view",
    "verb": "לחזק",
    "root": "ח.ז.ק",
    "binyan": "piel",
    "object_type": "possessive_suffix",
    "suffix_noun": "דעה",
    "suffix_preposition": "ב",
    "template": "⟨VERB⟩ ⟨DIR_OBJ⟩ ⟨SUFFIX_FORM⟩",
    "example": "התגובות חיזקו אותו בדעתו",
    "negated": false,
    "literal_sg": "{s} strengthens {o} in {p} opinion",
    "literal_pl": "{s} strengthen {o} in {p} opinion",
    "literal_past": "{s} strengthened {o} in {p} opinion",
    "literal_future": "{s} will strengthen {o} in {p} opinion",
    "showMeaning": true,
    "suffix_forms": {
      "1sg": "בדעתי",
      "2msg": "בדעתך",
      "2fsg": "בדעתך",
      "3msg": "בדעתו",
      "3fsg": "בדעתה",
      "1pl": "בדעתנו",
      "2mpl": "בדעתכם",
      "2fpl": "בדעתכן",
      "3mpl": "בדעתם",
      "3fpl": "בדעתן"
    },
    "conjugations": {
      "present": { "msg": "מחזק", "fsg": "מחזקת", "mpl": "מחזקים", "fpl": "מחזקות" },
      "past":    { "msg": "חיזק", "fsg": "חיזקה", "mpl": "חיזקו", "fpl": "חיזקו" },
      "future":  { "msg": "יחזק", "fsg": "תחזק", "mpl": "יחזקו", "fpl": "יחזקו" }
    }
  }
];

  // Normalize the runtime aliases and expose an explicit pointing contract.
  // A reviewed entry must supply a complete pointed paradigm and provenance;
  // unreviewed entries deliberately fall back to plain Hebrew in the game.
  return raw.map(function (item) {
    return Object.assign({}, item, {
      present_tense: item.conjugations.present,
      past_tense: item.conjugations.past || null,
      future_tense: item.conjugations.future || null,
      present_tense_niqqud: item.conjugations_niqqud?.present || null,
      past_tense_niqqud: item.conjugations_niqqud?.past || null,
      future_tense_niqqud: item.conjugations_niqqud?.future || null,
      english_meaning: item.english,
      niqqud_status: item.niqqud_status || "unreviewed",
      niqqud_sources: Array.isArray(item.niqqud_sources) ? item.niqqud_sources.slice() : [],
    });
  });
})();

if (typeof globalThis !== "undefined") {
  globalThis.HEBREW_IDIOMS = HEBREW_IDIOMS;
}
