(function initIvriQuestAppBootstrapRuntime(global) {
"use strict";

const app = global.IvriQuestApp = global.IvriQuestApp || {};
const bootstrapRuntime = app.bootstrapRuntime = app.bootstrapRuntime || {};

bootstrapRuntime.createElementRegistry = bootstrapRuntime.createElementRegistry || function createElementRegistry(document) {
  return {
    appShell: document.querySelector(".app-shell"),
    shellTopbar: document.querySelector(".shell-topbar"),
    shellTopTitle: document.querySelector("#shellTopTitle"),
    shellGameplayPill: document.querySelector("#shellGameplayPill"),
    shellGameplayTime: document.querySelector("#shellGameplayTime"),
    shellGameplayCombo: document.querySelector("#shellGameplayCombo"),
    shellHomeBtn: document.querySelector("#shellHomeBtn"),
    routeButtons: Array.from(document.querySelectorAll("[data-route]")),
    homeView: document.querySelector("#homeView"),
    homeDashboard: document.querySelector("#homeDashboard"),
    homeLessonStage: document.querySelector("#homeLessonStage"),
    reviewView: document.querySelector("#reviewView"),
    settingsView: document.querySelector("#settingsView"),
    resultsView: document.querySelector("#resultsView"),
    homeLessonBtn: document.querySelector("#homeLessonBtn"),
    homeSentenceBankBtn: document.querySelector("#homeSentenceBankBtn"),
    homeShemaBtn: document.querySelector("#homeShemaBtn"),
    homeVerbMatchBtn: document.querySelector("#homeVerbMatchBtn"),
    homeAbbreviationBtn: document.querySelector("#homeAbbreviationBtn"),
    sentenceBankBtn: document.querySelector("#sentenceBankBtn"),
    lessonBtn: document.querySelector("#lessonBtn"),
    verbMatchBtn: document.querySelector("#verbMatchBtn"),
    abbreviationBtn: document.querySelector("#abbreviationBtn"),
    homeBtn: document.querySelector("#homeBtn"),
    gamePicker: document.querySelector("#gamePicker"),
    homeLangToggle: document.querySelector("#homeLangToggle"),
    homeLangValue: document.querySelector("#homeLangValue"),
    homeThemeToggle: document.querySelector("#homeThemeToggle"),
    homeThemeValue: document.querySelector("#homeThemeValue"),
    homeNiqqudToggle: document.querySelector("#homeNiqqudToggle"),
    homeNiqqudValue: document.querySelector("#homeNiqqudValue"),
    homeSoundToggle: document.querySelector("#homeSoundToggle"),
    homeSoundValue: document.querySelector("#homeSoundValue"),
    homeSpeechToggle: document.querySelector("#homeSpeechToggle"),
    homeSpeechValue: document.querySelector("#homeSpeechValue"),
    poolMeta: document.querySelector("#poolMeta"),
    langToggle: document.querySelector("#langToggle"),
    themeToggle: document.querySelector("#themeToggle"),
    soundToggle: document.querySelector("#soundToggle"),
    speechToggle: document.querySelector("#speechToggle"),
    feedbackSurveyLink: document.querySelector("#feedbackSurveyLink"),
    lessonProgressBar: document.querySelector("#lessonProgressBar"),
    lessonProgressFill: document.querySelector("#lessonProgressFill"),
    lessonTitleRow: document.querySelector("#lessonTitleRow"),
    modeTitle: document.querySelector("#modeTitle"),
    promptCard: document.querySelector(".prompt-card"),
    promptRootEmoji: document.querySelector("#promptRootEmoji"),
    promptLabel: document.querySelector("#promptLabel"),
    promptHint: document.querySelector("#promptHint"),
    promptFunctionHint: document.querySelector("#promptFunctionHint"),
    promptText: document.querySelector("#promptText"),
    promptSpeechBtn: document.querySelector("#promptSpeechBtn"),
    niqqudToggle: document.querySelector("#niqqudToggle"),
    choiceContainer: document.querySelector("#choiceContainer"),
    lessonFooter: document.querySelector("#lessonFooter"),
    feedbackTray: document.querySelector("#feedbackTray"),
    feedbackSentence: document.querySelector("#feedbackSentence"),
    feedbackDetail: document.querySelector("#feedbackDetail"),
    stickyLessonActions: document.querySelector("#stickyLessonActions"),
    nextBtn: document.querySelector("#nextBtn"),
    masterVerbBtn: document.querySelector("#masterVerbBtn"),
    resetProgress: document.querySelector("#resetProgress"),
    homeDomainPerformance: document.querySelector("#homeDomainPerformance"),
    homeModePerformance: document.querySelector("#homeModePerformance"),
    reviewDomainPerformance: document.querySelector("#reviewDomainPerformance"),
    reviewModePerformance: document.querySelector("#reviewModePerformance"),
    mostMissedList: document.querySelector("#mostMissedList"),
    mostMissedEmpty: document.querySelector("#mostMissedEmpty"),
    reviewPanelCard: document.querySelector("#reviewPanelCard"),
    reviewPanelToggle: document.querySelector("#reviewPanelToggle"),
    settingsCard: document.querySelector("#settingsCard"),
    settingsToggle: document.querySelector("#settingsToggle"),
    resultsTitle: document.querySelector("#resultsTitle"),
    resultsNote: document.querySelector("#resultsNote"),
    resultsSummary: document.querySelector("#resultsSummary"),
    resultsContinueBtn: document.querySelector("#resultsContinueBtn"),
    resultsReviewBtn: document.querySelector("#resultsReviewBtn"),
    resultsHomeBtn: document.querySelector("#resultsHomeBtn"),
    reviewTabButtons: Array.from(document.querySelectorAll("[data-review-tab]")),
    reviewOverviewPanel: document.querySelector("#reviewOverviewPanel"),
    reviewTroublePanel: document.querySelector("#reviewTroublePanel"),
    reviewWordBankPanel: document.querySelector("#reviewWordBankPanel"),
    reviewStatDue: document.querySelector("#reviewStatDue"),
    reviewStatMastered: document.querySelector("#reviewStatMastered"),
    reviewStatSentences: document.querySelector("#reviewStatSentences"),
    reviewStatLetters: document.querySelector("#reviewStatLetters"),
    worstSentencesList: document.querySelector("#worstSentencesList"),
    worstSentencesEmpty: document.querySelector("#worstSentencesEmpty"),
    hardestVerbsList: document.querySelector("#hardestVerbsList"),
    hardestVerbsEmpty: document.querySelector("#hardestVerbsEmpty"),
    weakestLettersList: document.querySelector("#weakestLettersList"),
    weakestLettersEmpty: document.querySelector("#weakestLettersEmpty"),
    wordBankSearch: document.querySelector("#wordBankSearch"),
    wordBankFilters: document.querySelector("#wordBankFilters"),
    wordBankCount: document.querySelector("#wordBankCount"),
    wordBankList: document.querySelector("#wordBankList"),
    wordBankEmpty: document.querySelector("#wordBankEmpty"),
    lessonStartIntro: document.querySelector("#lessonStartIntro"),
    sentenceBankIntro: document.querySelector("#sentenceBankIntro"),
    lessonStartContinue: document.querySelector("#lessonStartContinue"),
    secondChanceIntro: document.querySelector("#secondChanceIntro"),
    secondChanceContinue: document.querySelector("#secondChanceContinue"),
    verbMatchIntro: document.querySelector("#verbMatchIntro"),
    verbMatchContinue: document.querySelector("#verbMatchContinue"),
    abbreviationIntro: document.querySelector("#abbreviationIntro"),
    abbreviationContinue: document.querySelector("#abbreviationContinue"),
    homeAdvConjBtn: document.querySelector("#homeAdvConjBtn"),
    advConjBtn: document.querySelector("#advConjBtn"),
    advConjIntro: document.querySelector("#advConjIntro"),
    homePrepositionsBtn: document.querySelector("#homePrepositionsBtn"),
    prepositionsBtn: document.querySelector("#prepositionsBtn"),
    prepositionsIntro: document.querySelector("#prepositionsIntro"),
    homeBinyanBoardBtn: document.querySelector("#homeBinyanBoardBtn"),
    binyanBoardBtn: document.querySelector("#binyanBoardBtn"),
    binyanBoardIntro: document.querySelector("#binyanBoardIntro"),
    homeHandwritingBtn: document.querySelector("#homeHandwritingBtn"),
    handwritingBtn: document.querySelector("#handwritingBtn"),
    handwritingIntro: document.querySelector("#handwritingIntro"),
    welcomeModal: document.querySelector("#welcomeModal"),
    welcomeModalCloseBtn: document.querySelector("#welcomeModalCloseBtn"),
    welcomeSurveyLink: document.querySelector("#welcomeSurveyLink"),
    leaveSessionConfirm: document.querySelector("#leaveSessionConfirm"),
    leaveSessionStayBtn: document.querySelector("#leaveSessionStayBtn"),
    leaveSessionConfirmBtn: document.querySelector("#leaveSessionConfirmBtn"),
    translatable: Array.from(document.querySelectorAll("[data-i18n]")),
  };
};

bootstrapRuntime.createInitialState = bootstrapRuntime.createInitialState || function createInitialState(options) {
  const {
    storageKeys,
    loadJson,
    restoredUi,
    language,
    theme,
    audio,
    speech,
    welcomeModalSeen,
  } = options;

  return {
    progress: loadJson(storageKeys.progress, {}),
    sentenceProgress: loadJson(storageKeys.sentenceProgress, {}),
    language,
    theme,
    audio,
    speech,
    route: restoredUi.route || "home",
    lastPlayedMode: restoredUi.lastPlayedMode || "lesson",
    reviewTab: ["overview", "trouble", "wordbank"].includes(restoredUi.reviewTab) ? restoredUi.reviewTab : "overview",
    wordBank: { search: "", domain: "all" },
    mode: "home",
    currentQuestion: null,
    sessionScore: 0,
    sessionStreak: 0,
    showNiqqudInline: false,
    welcomeModalOpen: welcomeModalSeen !== true,
    leaveConfirmOpen: false,
    pendingLeaveRoute: "home",
    summary: {
      active: false,
      game: "",
      titleKey: "",
      titleVars: {},
      scoreKey: "",
      scoreVars: {},
      noteKey: "",
      noteVars: {},
      correctCount: 0,
      incorrectCount: 0,
      elapsedSeconds: 0,
      mistakes: [],
      corrects: [],
    },
    lesson: {
      active: false,
      currentRound: 0,
      secondChanceCurrent: 0,
      secondChanceTotal: 0,
      startMs: 0,
      elapsedSeconds: 0,
      timerId: null,
      askedWordIds: [],
      domainCounts: {},
      missedWordIds: [],
      reviewQueue: [],
      inReview: false,
      lessonStartIntroActive: false,
      secondChanceIntroActive: false,
      optionHistory: {},
      wrongAnswers: 0,
      sessionMistakeIds: [],
    },
    sentenceBank: {
      active: false,
      introActive: false,
      inReview: false,
      currentRound: 0,
      secondChanceCurrent: 0,
      secondChanceTotal: 0,
      startMs: 0,
      elapsedSeconds: 0,
      timerId: null,
      askedSentenceIds: [],
      reviewQueue: [],
      currentQuestion: null,
      wrongAnswers: 0,
      sessionMistakeKeys: [],
      availableScore: 0,
      shemaMode: false,
    },
    abbreviation: {
      active: false,
      currentRound: 0,
      startMs: 0,
      elapsedSeconds: 0,
      timerId: null,
      askedEntryIds: [],
      introActive: false,
      currentQuestion: null,
      wrongAnswers: 0,
      sessionMistakeIds: [],
    },
    advConj: {
      active: false,
      introActive: false,
      currentRound: 0,
      startMs: 0,
      elapsedSeconds: 0,
      timerId: null,
      questionQueue: [],
      currentQuestion: null,
      wrongAnswers: 0,
      sessionMistakeIds: [],
      sessionMistakes: [],
      inReview: false,
      reviewQueue: [],
      secondChanceCurrent: 0,
      secondChanceTotal: 0,
    },
    prepositions: {
      active: false,
      introActive: false,
      currentRound: 0,
      startMs: 0,
      elapsedSeconds: 0,
      timerId: null,
      questionQueue: [],
      currentQuestion: null,
      wrongAnswers: 0,
      sessionMistakes: [],
      inReview: false,
      reviewQueue: [],
      secondChanceCurrent: 0,
      secondChanceTotal: 0,
    },
    binyanBoard: {
      active: false,
      introActive: false,
      deck: [],
      distractorPool: [],
      totalRoots: 0,
      clearedCount: 0,
      activeRootId: "",
      roundForms: [],
      roundIndex: 0,
      currentQuestion: null,
      correctCount: 0,
      wrongAnswers: 0,
      sessionMistakeIds: [],
      inReview: false,
      reviewQueue: [],
      secondChanceCurrent: 0,
      secondChanceTotal: 0,
      startMs: 0,
      elapsedSeconds: 0,
      timerId: null,
    },
    match: {
      active: false,
      verbQueue: [],
      totalVerbs: 0,
      currentVerbIndex: 0,
      currentVerb: null,
      pairs: [],
      remainingPairs: [],
      leftCards: [],
      rightCards: [],
      layoutMode: "classic",
      selectedLeftId: null,
      selectedRightId: null,
      mismatchedCardIds: [],
      matchedCardIds: [],
      matchedPairIds: [],
      isResolving: false,
      nextCardId: 1,
      combo: 0,
      bestCombo: 0,
      matchedCount: 0,
      totalPairs: 0,
      startMs: 0,
      elapsedSeconds: 0,
      timerId: null,
      verbIntroActive: false,
      sessionMatched: 0,
      sessionTotalPairs: 0,
      currentVerbHadMismatch: false,
      eligibleMasterWordId: "",
      mismatchCount: 0,
      sessionMistakeIds: [],
      sessionMistakeForms: [],
    },
    handwriting: {
      active: false,
      introActive: false,
      startMs: 0,
      elapsedSeconds: 0,
      timerId: null,
      rounds: [],
      roundIndex: 0,
      totalRounds: 0,
      cellIndex: 0,
      currentStrokes: [],
      attemptsThisCell: 0,
      cellRecorded: false,
      lastTone: "",
      correctCount: 0,
      mismatchCount: 0,
      sessionMistakeIds: [],
      isResolving: false,
    },
    wordMatch: {
      active: false,
      introActive: false,
      game: "",
      startMs: 0,
      elapsedSeconds: 0,
      timerId: null,
      pairs: [],
      remainingPairs: [],
      leftCards: [],
      rightCards: [],
      selectedLeftId: null,
      selectedRightId: null,
      mismatchedCardIds: [],
      matchedCardIds: [],
      matchedPairIds: [],
      isResolving: false,
      nextCardId: 1,
      matchedCount: 0,
      totalPairs: 0,
      combo: 0,
      bestCombo: 0,
      mismatchCount: 0,
      sessionMistakeIds: [],
    },
  };
};

})(typeof window !== "undefined" ? window : globalThis);
