(function initIvriQuestAppBootstrapData(global) {
"use strict";

const app = global.IvriQuestApp = global.IvriQuestApp || {};
const bootstrapData = app.bootstrapData = app.bootstrapData || {};

bootstrapData.buildDomainByCategoryMap = bootstrapData.buildDomainByCategoryMap || function buildDomainByCategoryMap(domains) {
  const categoryMap = new Map();
  domains.forEach((domain) => {
    domain.categories.forEach((category) => {
      categoryMap.set(category, domain.id);
    });
  });
  return categoryMap;
};

bootstrapData.I18N = bootstrapData.I18N || {
  en: {
    app: {
      title: "IvritElite | Advanced Hebrew Trainer",
      name: "IvritElite",
    },
    nav: {
      home: "Home",
      learn: "Learn",
      review: "Review",
      settings: "Settings",
      results: "Results",
    },
    top: {
      eyebrow: "Browser-Only Hebrew Mastery",
      subhead: "Advanced vocabulary trainer inspired by Duolingo, tuned for real-world fluency.",
      accuracy: "Accuracy",
      streak: "Current Streak",
    },
    controls: {
      settings: "Settings",
      interface: "Interface",
      lightMode: "Light Mode",
      darkMode: "Dark Mode",
      reset: "Reset Progress",
      resetConfirm: "Reset all spaced-repetition progress and streak data?",
    },
    perf: {
      eyebrow: "Performance Snapshot",
      title: "Vocabulary Type",
      note: "Since your last progress reset",
    },
    session: {
      eyebrow: "Session",
      mixedTitle: "Translation",
      secondChanceTitle: "Translation Review",
      sentenceBankTitle: "Sentences",
      sentenceBankSecondChanceTitle: "Sentences Review",
      shemaTitle: "Shema",
      shemaSecondChanceTitle: "Shema Review",
      verbMatchTitle: "Conjugation",
      abbreviationTitle: "Abbreviation",
      round: "Round: {current}/{total}",
      secondChanceProgress: "Second chance: {current}/{total}",
      secondChanceContinue: "Start Second Chance",
      words: "Words: {count}",
      timer: "Time: {seconds}s",
      score: "Score: {score}",
      combo: "Combo x{count}",
      start: "Start Translation",
      restart: "Restart Translation",
      sentenceBankStart: "Start Sentences",
      verbMatchStart: "Start Conjugation",
      verbMatchRestart: "Restart Conjugation",
      abbreviationStart: "Start Abbreviation",
      abbreviationRestart: "Restart Abbreviation",
      nextVerb: "Next Verb",
      clear: "Clear",
      hint: "Hint",
      hideHint: "Hide Hint",
      check: "Check",
      skip: "Skip",
      submit: "Submit",
      next: "Next",
      viewResults: "View Results",
      backHome: "Back to Home",
      leaveTitle: "Leave this game?",
      leaveBody: "If you leave this game now, you'll lose your progress so far.",
      keepPlaying: "Keep Playing",
      leaveGame: "Lose Progress",
      starting: "Starting...",
      playAgain: "Play Again",
    },
    home: {
      title: "Choose A Game",
      status: "Pick a mode to start.",
      label: "Homepage",
      prompt: "Choose one of the game modes below.",
    },
    dashboard: {
      eyebrow: "Daily Focus",
      greeting: "Welcome back",
      lessonsEyebrow: "Lesson Options",
      lessonsTitle: "Choose Your Lesson",
      statsEyebrow: "Stats Summary",
      statsTitle: "Current Snapshot",
      user: "Learner",
      userPlaceholder: "You",
      learned: "Total Vocab Learned",
      modeEyebrow: "Interface",
      modeTitle: "Options",
      continue: "Continue Lesson",
      review: "Review Mistakes",
      settings: "Open Settings",
      ready: "Ready to jump back in.",
      active: "Lesson in progress.",
      idle: "No lesson in progress.",
      activeMode: "Current focus",
      currentMode: "Mode",
      language: "Language",
      theme: "Theme",
      niqqud: "Nikud",
      on: "On",
      off: "Off",
    },
    learn: {
      idleLabel: "Learn",
      idlePrompt: "Pick a mode to start a focused session.",
    },
    game: {
      translationName: "Translation",
      translationNote: "Match Hebrew words to their English meanings.",
      sentenceBankName: "Sentences",
      sentenceBankNote: "Build full translations from a shuffled word bank.",
      shemaName: "Shema",
      shemaNote: "Listen to a Hebrew sentence and build what you hear.",
      conjugationName: "Conjugation",
      conjugationNote: "Match English forms to Hebrew conjugations.",
      bubbleConjName: "Bubble Conjugation",
      bubbleConjNote: "Pop floating English and Hebrew conjugation pairs.",
      abbreviationName: "Abbreviation",
      abbreviationNote: "Match Hebrew abbreviations to their English meanings.",
      advConjName: "Conjugation+",
      advConjNote: "Conjugate both subject and object of Hebrew verbal idioms.",
      prepositionsName: "Prepositions",
      prepositionsNote: "Pick the preposition each verb or expression governs, inflected for its object.",
      binyanName: "Binyanim",
      binyanNote: "Pick a root, then guess what each of its binyanim means.",
      handwritingName: "Handwriting",
      handwritingNote: "Trace cursive Hebrew letters by hand.",
    },
    handwriting: {
      check: "Check",
      undo: "Undo",
      clear: "Clear",
      skip: "Skip",
      feedbackPass: "Nice! Score: {score}",
      feedbackRetry: "Not quite ({score}). Follow the numbered guide and try again.",
    },
    binyan: {
      cleared: "Cleared",
      formCount: "{count} forms",
      function: {
        simple: "Simple active",
        passive: "Passive",
        middle: "Middle",
        intensive: "Intensive (active)",
        causative: "Causative",
        reflexive: "Reflexive",
        reciprocal: "Reciprocal",
        resultative: "Resultative",
        inchoative: "Inchoative",
        active: "Active",
      },
      functionHint: {
        hidden: "Hint",
        revealTitle: "Show hint",
        hideTitle: "Hide hint",
        paal: "Basic Active",
        nifal: "Passive/Middle",
        piel: "Intensive/Causative Active",
        pual: "Passive Intensive/Causative",
        hifil: "Causative Active",
        hufal: "Causative Passive",
        hitpael: "Reflexive/Reciprocal",
      },
      functionClinic: {
        simple: "a basic active meaning",
        passive: "a passive meaning",
        middle: "a passive or state-change meaning",
        intensive: "an intensive active meaning",
        causative: "a causative meaning",
        reflexive: "a reflexive meaning",
        reciprocal: "a reciprocal meaning",
        resultative: "a result/resulting-state meaning",
        inchoative: "a becoming/change-of-state meaning",
        active: "an active meaning",
      },
      teaching: {
        noMetathesis: "No spelling change here: ל is not a sibilant, so the ת stays in place.",
        sibilantMetathesis: "Because the root starts with ס, the ת moves after it: התסדר becomes הסתדר.",
        emphaticMetathesis: "Because the root starts with צ, the ת moves and changes to ט: התצלם becomes הצטלם.",
        hollowFactitiveActive: "This hollow root uses a special intensive/causative pattern here.",
        hollowFactitivePassive: "This hollow root uses the matching passive pattern here.",
        hollowReflexive: "This hollow root uses a special reflexive pattern here.",
        peNunAssimilation: "Because this is a פ\"נ root, the נ disappears into a dagesh: הנפיל becomes הִפִּיל.",
        peNunNoAssimilation: "Here the נ stays put, because it follows the ת of the hitpa'el.",
        peYodConsonant: "The opening י stays a consonant after the ת, unlike the וֹ/וּ vowel in נושב, הושיב, and הושב.",
        voicedSibilantMetathesis: "Because the root starts with ז, the ת moves after it and changes to ד: התזמן becomes הזדמן.",
        peGuttural: "Because the root starts with the guttural ע, it cannot take a plain sheva: it takes a hataf vowel and the prefix vowel shifts to match (נעמד, העמיד, הועמד).",
        lamedAlefQuiescent: "The final א is silent (ל\"א): it takes no vowel of its own, and the vowel before it lengthens — מצא, נמצא.",
        ayinYodStrong: "Although ק־י־ם is ע\"י, its yod acts as a full consonant, so the forms look regular (קִיֵּם, הִתְקַיֵּם) — unlike the hollow ק־ו־ם, which uses the special קוֹמֵם / הִתְקוֹמֵם patterns.",
        geminateHifil: "In a geminate (ע\"ע) root the doubled radical collapses, so the hif'il is הֵסֵב — not the expected הִסְבִּיב.",
        geminateHitpaelSibilant: "Geminate (ע\"ע) hitpa'el: the base הִתְסוֹבֵב also swaps ת and ס (sibilant metathesis), giving הִסְתּוֹבֵב.",
        geminateHitpael: "Geminate (ע\"ע) hitpa'el: the doubled radical gives the CoCeC shape הִתְמוֹדֵד; מ is not a sibilant, so there is no metathesis.",
      },
    },
    prompt: {
      lesson: "Lesson",
      start: 'Press "Start Translation" to begin.',
      sentenceBankStart: "Build the translation by dragging words into place, or tap a word and then a blank.",
      sentenceBankDragTip: "Tip: drag answer blocks to any slot in the sentence.",
      shemaListen: "Listen to the sentence, then build what you hear.",
      shemaPlay: "🔊 Play sentence",
      shemaPlaySlow: "🐢 Slower",
      verbMatchStart: 'Press "Start Conjugation" to practice conjugations and root forms.',
      abbreviation: "Abbreviation",
      abbreviationStart: 'Press "Start Abbreviation" to guess meanings and see full Hebrew expansions.',
      handwritingStart: 'Press "Handwriting" on the home screen to trace cursive letters.',
      abbreviationHeToEn: "Hebrew abbreviation -> English meaning",
      abbreviationEnToHe: "English meaning -> Hebrew abbreviation",
      noSentenceBankTitle: "No sentence bank loaded",
      noSentenceBankBody: "Ask the agent to update sentence-bank-data.js, then reload.",
      noAbbreviationTitle: "No abbreviations loaded",
      noAbbreviationBody: "Ask the agent to update abbreviation-data.js, then reload.",
      noVocabTitle: "No vocabulary loaded",
      noVocabBody: "Ask the agent to update vocab-data.js, then reload.",
      masteredOnlyTitle: "Translation pool is empty",
      masteredOnlyBody: "All words are currently mastered for translation. Reset progress in Settings to restore them.",
      showNiqqud: "Show Nikud",
      hideNiqqud: "Hide Nikud",
      toEnglish: "Translate to English",
      toHebrew: "Translate to Hebrew",
      reviewToEnglish: "Second Chance: Translate to English",
      reviewToHebrew: "Second Chance: Translate to Hebrew",
    },
    audio: {
      label: "Sound Effects",
      on: "On",
      off: "Off",
    },
    speech: {
      label: "Speech",
      on: "On",
      off: "Off",
      unavailable: "Unavailable",
      tipSelectHebrewFirst: "Tip: select the Hebrew first to hear it aloud.",
      playPromptAria: "Play Hebrew prompt",
      playPromptTitle: "Play Hebrew prompt",
    },
    feedback: {
      translationCorrectToEnglish: 'Correct. {hebrew} means "{english}".',
      translationWrongToEnglish: 'Not quite. {hebrew} means "{english}".',
      translationCorrectToHebrew: "Correct. The Hebrew answer is {answer}.",
      translationWrongToHebrew: "Not quite. The Hebrew answer is {answer}.",
      sentenceBankCorrectToEnglish: "Correct. The English sentence is {answer}",
      sentenceBankWrongToEnglish: "Not quite. The English sentence is {answer}",
      sentenceBankCorrectToHebrew: "Correct. The Hebrew sentence is {answer}",
      sentenceBankWrongToHebrew: "Not quite. The Hebrew sentence is {answer}",
      shemaCorrect: "Correct. You heard {answer}",
      shemaWrong: "Not quite. The sentence was {answer}",
      shemaMeaning: "Meaning: {english}",
      sentenceBankSingleWordTip: "Correct word: {correctWord} = {correctMeaning}. Chosen word: {chosenWord} = {chosenMeaning}.",
      sentenceBankGameTip: "Tip: {detail}",
      abbreviationCorrectToEnglish: 'Correct. {abbr} stands for "{english}".',
      abbreviationWrongToEnglish: 'Not quite. {abbr} stands for "{english}".',
      abbreviationCorrectToHebrew: "Correct. The abbreviation is {abbr}.",
      abbreviationWrongToHebrew: "Not quite. The abbreviation is {abbr}.",
      abbreviationExpansionDetail: "The full Hebrew is {expansion}.",
      lessonDone: "Lesson complete. Final score {score}/{total}.",
      reviewAdded: "Second chance rounds included: {count}.",
      startAnother: 'Press "Start Translation" to run another round.',
      reviewIntro: "Second chance round: retry {count} words you missed.",
      matchDoneVerb: "Verb complete: {verb}.",
      matchDoneAll: "Conjugation session complete. Verbs covered: {count}.",
      advConjCorrectSentence: "Correct. The sentence is {answer}.",
      advConjWrongSentence: "Not quite. The sentence is {answer}.",
      advConjMeaningDetail: "Everyday meaning: {meaning}.",
      prepositionsCorrect: "Correct. It's {answer}.",
      prepositionsWrong: "Not quite. The answer is {answer}.",
      prepositionsDetail: "Meaning: {meaning}.",
      binyanCorrect: "Correct: {form} means {gloss}.",
      binyanWrong: "Not quite: {form} means {gloss}.",
    },
    summary: {
      resultsHeader: "Session Results",
      lessonTitle: "Translation Complete",
      sentenceBankTitle: "Sentences Complete",
      shemaTitle: "Shema Complete",
      matchTitle: "Conjugation Complete",
      abbreviationTitle: "Abbreviation Complete",
      advConjTitle: "Conjugation+ Complete",
      prepositionsTitle: "Prepositions Complete",
      binyanTitle: "Binyanim Complete",
      binyanNote: "Roots cleared: {roots}",
      handwritingTitle: "Handwriting Complete",
      handwritingNote: "Sentences: {sentences}",
      score: "Score: {score}/{total}",
      lessonNote: "Second-chance rounds: {count}",
      lessonNoteNone: "No second-chance rounds this run.",
      matchNote: "Verbs: {verbs} | Best combo: {combo} | Time: {seconds}s",
      abbreviationNote: "Rounds: {rounds} | Time: {seconds}s",
      wordMatchNote: "Matched: {matched} | Best combo: {combo} | Time: {seconds}s",
      thumbsText: "Great work",
    },
    review: {
      queueEyebrow: "Revenge Queue",
      queueTitle: "Review Queue",
      queueEmpty: "No review items waiting.",
      pending: "{count} items waiting for revenge mode.",
      empty: "Nothing is waiting in the current review queue.",
      analyticsEyebrow: "Category Analytics",
      analyticsTitle: "Category Performance",
      missedTitle: "Mistakes To Revenge",
    },
    settings: {
      title: "Settings",
      note: "Adjust language, theme, sound effects, speech, and inline nikud.",
      language: "Language",
      feedbackSurvey: "Feedback survey",
      niqqud: "Inline Nikud",
      theme: "Theme",
      resetTitle: "Reset Progress",
      resetNote: "Clear saved spacing, streaks, and review data.",
    },
    welcome: {
      title: "Welcome to IvritElite!",
      line1: "This is a new app for advanced Hebrew learning.",
      surveyPrefix: "We would love to hear your feedback in ",
      surveyLink: "this survey",
      surveySuffix: ".",
      line2: "You can also access the survey from the Settings page.",
      close: "Close",
      closeAria: "Close welcome message",
    },
    results: {
      continue: "Play Again",
      correct: "Correct",
      incorrect: "Incorrect",
      time: "Time",
      score: "Score",
      accuracy: "Accuracy",
      reviewRounds: "Review Rounds",
      rounds: "Rounds",
      verbs: "Verbs",
      bestCombo: "Best Combo",
      mistakes: "Session Mistakes",
      mistakeClinic: "Mistake Clinic",
      correctAnswers: "Correct Answers",
      clinic: "{note}",
      sentenceClinic: "Tip: {note}",
      prepositionClinic: "Pattern: {trigger} takes {prep}; with {object}, use {answer}.",
      advConjClinic: "Check both parts: subject {subject} in {tense}, object {object}.",
      binyanClinic: "Pattern: {binyan} carries {function} here.",
      reviewPerformance: "Review Performance",
      niceJob: "Nice job!",
      roomToImprove: "There's room to improve",
      amazing: "Amazing!",
      noMistakes: "No mistakes in this session.",
      moreForms: "+{count} more",
    },
    match: {
      prompt: "Match the pairs",
      verbLabel: "Verb",
      leftColumn: "English",
      rightColumn: "Hebrew",
      progress: "Pairs: {current}/{total}",
      verbProgress: "Verb: {current}/{total}",
      timer: "Time: {seconds}s",
      combo: "Combo x{count}",
      roundDone: "Great. You matched all forms for {verb}.",
      noVerbs: "No verbs found in the vocabulary list.",
      validatedNote: "Using stored validated forms for this verb.",
      generatedNote: "Using validated generated forms for an explicitly safe verb.",
    },
    pool: {
      summary: "Translation pool: {pool} words with nikud ({total} in lexicon).",
      expansion: "Expansion tracks mapped: {count}.",
      tempProgress: "Progress is temporary in this browser mode (storage unavailable).",
      fallback: "Fallback vocab loaded because vocab-data.js was not available.",
    },
    missed: {
      title: "Most Missed",
      note: "Words you have missed most often.",
      empty: "No misses yet.",
      misses: "{count} misses",
    },
    mastered: {
      open: "Mastered List",
      title: "Mastered Words",
      note: "Mastered words are excluded from Translation but still used in Conjugation.",
      selectHint: "Select words to restore to translation testing.",
      empty: "No mastered words yet.",
      restoreSelected: "Restore Selected",
      close: "Close",
      moveCurrent: "Move To Mastered",
      streakStatus: "Clean streak: {count}/{target}",
      ready: "{verb} reached {target} clean rounds. You can move it to Mastered.",
      added: "{word} moved to Mastered.",
      restored: "Restored {count} words to translation.",
    },
    domain: {
      colloquial: "Colloquial & Street",
      everyday: "Everyday Functional",
      professional: "Professional",
      formal: "Formal & Analytical",
    },
  },
  he: {
    app: {
      title: "עברית עילית | מאמן עברית מתקדם",
      name: "עברית עילית",
    },
    nav: {
      home: "בית",
      learn: "לומדים",
      review: "סקירה",
      settings: "הגדרות",
      results: "תוצאות",
    },
    top: {
      eyebrow: "שליטה בעברית בדפדפן בלבד",
      subhead: "מאמן אוצר מילים מתקדם בהשראת Duolingo, מותאם לשטף בשימוש אמיתי.",
      accuracy: "דיוק",
      streak: "רצף נוכחי",
    },
    controls: {
      settings: "הגדרות",
      interface: "ממשק",
      lightMode: "מצב בהיר",
      darkMode: "מצב כהה",
      reset: "איפוס התקדמות",
      resetConfirm: "לאפס את כל התקדמות החזרות והסטטיסטיקות?",
    },
    perf: {
      eyebrow: "תמונת ביצועים",
      title: "סוג אוצר מילים",
      note: "מאז איפוס ההתקדמות האחרון",
    },
    session: {
      eyebrow: "אימון",
      mixedTitle: "תרגום",
      secondChanceTitle: "סבב הזדמנות שנייה",
      sentenceBankTitle: "משפטים",
      sentenceBankSecondChanceTitle: "חזרה על משפטים",
      shemaTitle: "שמע",
      shemaSecondChanceTitle: "חזרה על שמע",
      verbMatchTitle: "נטיות",
      abbreviationTitle: "ר״ת",
      round: "סבב: {current}/{total}",
      secondChanceProgress: "הזדמנות שנייה: {current}/{total}",
      secondChanceContinue: "התחל הזדמנות שנייה",
      words: "מילים: {count}",
      timer: "זמן: {seconds}ש׳",
      score: "ציון: {score}",
      combo: "קומבו x{count}",
      start: "התחל תרגום",
      restart: "התחל תרגום מחדש",
      sentenceBankStart: "התחל משפטים",
      verbMatchStart: "התחל נטיות",
      verbMatchRestart: "התחל נטיות מחדש",
      abbreviationStart: "התחל ר״ת",
      abbreviationRestart: "התחל ר״ת מחדש",
      nextVerb: "לפועל הבא",
      clear: "נקה",
      hint: "רמז",
      hideHint: "הסתר רמז",
      check: "בדוק",
      skip: "דלג",
      submit: "שלח",
      next: "הבא",
      viewResults: "לתוצאות",
      backHome: "חזרה לעמוד הבית",
      leaveTitle: "לצאת מהמשחק?",
      leaveBody: "אם תצא עכשיו מהמשחק, תאבד את ההתקדמות שלך עד כה.",
      keepPlaying: "להמשיך לשחק",
      leaveGame: "לאבד התקדמות",
      starting: "מתחיל...",
      playAgain: "שחק שוב",
    },
    home: {
      title: "בחר משחק",
      status: "בחר מצב כדי להתחיל.",
      label: "דף הבית",
      prompt: "בחר אחד ממצבי המשחק כאן למטה.",
    },
    dashboard: {
      eyebrow: "פוקוס יומי",
      greeting: "ברוך שובך",
      lessonsEyebrow: "אפשרויות שיעור",
      lessonsTitle: "בחר שיעור",
      statsEyebrow: "סיכום נתונים",
      statsTitle: "תמונת מצב נוכחית",
      user: "לומד",
      userPlaceholder: "אתה",
      learned: "סך אוצר מילים שנלמד",
      modeEyebrow: "ממשק",
      modeTitle: "אפשרויות",
      continue: "המשך שיעור",
      review: "סקור טעויות",
      settings: "פתח הגדרות",
      ready: "מוכן לחזור לתרגול.",
      active: "יש שיעור פעיל.",
      idle: "אין כרגע שיעור פעיל.",
      activeMode: "פוקוס נוכחי",
      currentMode: "מצב",
      language: "שפה",
      theme: "ערכת נושא",
      niqqud: "ניקוד",
      on: "פועל",
      off: "כבוי",
    },
    learn: {
      idleLabel: "לומדים",
      idlePrompt: "בחר מצב כדי להתחיל סשן ממוקד.",
    },
    game: {
      translationName: "תרגום",
      translationNote: "התאם מילים בעברית למשמעות שלהן באנגלית.",
      sentenceBankName: "משפטים",
      sentenceBankNote: "בנה תרגומים מלאים ממאגר מילים מעורבב.",
      shemaName: "שמע",
      shemaNote: "האזן למשפט בעברית ובנה את מה ששמעת.",
      conjugationName: "נטיות",
      conjugationNote: "התאם בין נטיות באנגלית לנטיות בעברית.",
      bubbleConjName: "נטיות בועות",
      bubbleConjNote: "פוצץ זוגות מרחפים של נטיות באנגלית ובעברית.",
      abbreviationName: "ר״ת",
      abbreviationNote: "התאם ראשי תיבות בעברית למשמעות שלהם באנגלית.",
      advConjName: "נטיות+",
      advConjNote: "נטה גם את הנושא וגם את המושא של ביטויים פועלים עבריים.",
      prepositionsName: "מילות יחס",
      prepositionsNote: "בחר את מילת היחס שכל פועל או ביטוי דורש, מוטה לפי המושא.",
      binyanName: "בניינים",
      binyanNote: "בחרו שורש ונחשו מה משמעות כל אחד מהבניינים שלו.",
      handwritingName: "כתב יד",
      handwritingNote: "עקבו אחרי אותיות הכתב ותרגלו כתיבה ביד.",
    },
    handwriting: {
      check: "בדיקה",
      undo: "בטל",
      clear: "נקה",
      skip: "דלג",
      feedbackPass: "יפה! ציון: {score}",
      feedbackRetry: "כמעט ({score}). עקבו אחרי המספרים ונסו שוב.",
    },
    binyan: {
      cleared: "הושלם",
      formCount: "{count} צורות",
      function: {
        simple: "פשוט (פעיל)",
        passive: "סביל",
        middle: "אמצעי",
        intensive: "מוגבר (פעיל)",
        causative: "גורם",
        reflexive: "חוזר",
        reciprocal: "הדדי",
        resultative: "תוצאתי",
        inchoative: "התחלתי",
        active: "פעיל",
      },
      functionHint: {
        hidden: "רמז",
        revealTitle: "הצג רמז",
        hideTitle: "הסתר רמז",
        paal: "פעיל בסיסי",
        nifal: "סביל/אמצעי",
        piel: "פעיל אינטנסיבי/גורם",
        pual: "סביל אינטנסיבי/גורם",
        hifil: "פעיל גורם",
        hufal: "סביל גורם",
        hitpael: "חוזר/הדדי",
      },
      functionClinic: {
        simple: "משמעות פעילה בסיסית",
        passive: "משמעות סבילה",
        middle: "משמעות סבילה או שינוי מצב",
        intensive: "משמעות פעילה אינטנסיבית",
        causative: "משמעות גורמת",
        reflexive: "משמעות חוזרת",
        reciprocal: "משמעות הדדית",
        resultative: "משמעות תוצאתית",
        inchoative: "משמעות של התחלה או שינוי מצב",
        active: "משמעות פעילה",
      },
      teaching: {
        noMetathesis: "אין כאן שינוי כתיב: ל אינה אות שורקת, ולכן ת נשארת במקום.",
        sibilantMetathesis: "מכיוון שהשורש מתחיל ב־ס, האות ת עוברת אחריה: התסדר הופך ל־הסתדר.",
        emphaticMetathesis: "מכיוון שהשורש מתחיל ב־צ, האות ת זזה והופכת ל־ט: התצלם הופך ל־הצטלם.",
        hollowFactitiveActive: "בשורש חלול כזה משתמשים כאן בתבנית פעילה מיוחדת.",
        hollowFactitivePassive: "בשורש חלול כזה משתמשים כאן בתבנית סבילה מיוחדת.",
        hollowReflexive: "בשורש חלול כזה משתמשים כאן בתבנית חוזרת מיוחדת.",
        peNunAssimilation: "מכיוון שזהו שורש פ\"נ, האות נ נבלעת בדגש: הנפיל הופך ל־הִפִּיל.",
        peNunNoAssimilation: "כאן ה־נ נשארת במקום, מפני שהיא באה אחרי ת של ההתפעל.",
        peYodConsonant: "ה־י הפותחת נשארת עיצור אחרי ת, בניגוד לתנועת וֹ/וּ שב־נושב, הושיב והושב.",
        voicedSibilantMetathesis: "מכיוון שהשורש מתחיל ב־ז, האות ת עוברת אחריה והופכת ל־ד: התזמן הופך ל־הזדמן.",
        peGuttural: "מכיוון שהשורש מתחיל באות גרונית ע, היא אינה יכולה לקבל שווא רגיל: היא מקבלת חטף ותנועת התחילית משתנה בהתאם (נעמד, העמיד, הועמד).",
        lamedAlefQuiescent: "האות א הסופית נחה (ל\"א): היא אינה מקבלת תנועה משלה, והתנועה שלפניה מתארכת — מצא, נמצא.",
        ayinYodStrong: "אף ש־ק־י־ם הוא שורש ע\"י, ה־י מתפקדת כעיצור מלא, ולכן הצורות נראות רגילות (קִיֵּם, הִתְקַיֵּם) — בניגוד לשורש החלול ק־ו־ם, שמשתמש בתבניות המיוחדות קוֹמֵם / הִתְקוֹמֵם.",
        geminateHifil: "בשורש כפול (ע\"ע) האות הכפולה נבלעת, ולכן ההפעיל הוא הֵסֵב — ולא הִסְבִּיב הצפוי.",
        geminateHitpaelSibilant: "התפעל של שורש כפול (ע\"ע): הבסיס הִתְסוֹבֵב גם מחליף ת ו־ס (מטאתזיס של אות שורקת), ויוצא הִסְתּוֹבֵב.",
        geminateHitpael: "התפעל של שורש כפול (ע\"ע): האות הכפולה נותנת את התבנית הִתְמוֹדֵד; מ אינה אות שורקת, ולכן אין מטאתזיס.",
      },
    },
    prompt: {
      lesson: "שיעור",
      start: 'לחץ על "התחל תרגום" כדי להתחיל.',
      sentenceBankStart: "בנה את התרגום על ידי גרירת המילים למקום, או הקש על מילה ואז על רווח ריק.",
      sentenceBankDragTip: "טיפ: אפשר לגרור אבני תשובה לכל משבצת במשפט.",
      shemaListen: "האזן למשפט ובנה את מה ששמעת.",
      shemaPlay: "🔊 השמע משפט",
      shemaPlaySlow: "🐢 לאט יותר",
      verbMatchStart: 'לחץ על "התחל נטיות" כדי לתרגל נטיות ושמות שורש.',
      abbreviation: "קיצור",
      abbreviationStart: 'לחץ על "התחל ר״ת" כדי לנחש משמעות ולקבל את הפירוש המלא.',
      handwritingStart: 'לחצו על "כתב יד" במסך הבית כדי לתרגל אותיות בכתב.',
      abbreviationHeToEn: "קיצור בעברית -> משמעות באנגלית",
      abbreviationEnToHe: "משמעות באנגלית -> קיצור בעברית",
      noSentenceBankTitle: "אין מאגר משפטים טעון",
      noSentenceBankBody: "בקש מהסוכן לעדכן את sentence-bank-data.js ואז טען מחדש.",
      noAbbreviationTitle: "אין קיצורים טעונים",
      noAbbreviationBody: "בקש מהסוכן לעדכן את abbreviation-data.js ואז טען מחדש.",
      noVocabTitle: "אין אוצר מילים טעון",
      noVocabBody: "בקש מהסוכן לעדכן את vocab-data.js ואז טען מחדש.",
      masteredOnlyTitle: "אין מילים זמינות לתרגום",
      masteredOnlyBody: "כל המילים כרגע מנוסות לתרגום. אפס את ההתקדמות בהגדרות כדי להחזיר אותן.",
      showNiqqud: "הצג ניקוד",
      hideNiqqud: "הסתר ניקוד",
      toEnglish: "תרגם לאנגלית",
      toHebrew: "תרגם לעברית",
      reviewToEnglish: "הזדמנות שנייה: תרגם לאנגלית",
      reviewToHebrew: "הזדמנות שנייה: תרגם לעברית",
    },
    audio: {
      label: "אפקטים קוליים",
      on: "פועל",
      off: "כבוי",
    },
    speech: {
      label: "דיבור",
      on: "פועל",
      off: "כבוי",
      unavailable: "לא זמין",
      tipSelectHebrewFirst: "טיפ: בחר קודם את העברית כדי לשמוע אותה מוקראת.",
      playPromptAria: "השמע את ההנחיה בעברית",
      playPromptTitle: "השמע את ההנחיה בעברית",
    },
    feedback: {
      translationCorrectToEnglish: 'נכון. {hebrew} פירושו "{english}".',
      translationWrongToEnglish: 'לא בדיוק. {hebrew} פירושו "{english}".',
      translationCorrectToHebrew: "נכון. התשובה בעברית היא {answer}.",
      translationWrongToHebrew: "לא בדיוק. התשובה בעברית היא {answer}.",
      sentenceBankCorrectToEnglish: "נכון. המשפט באנגלית הוא {answer}",
      sentenceBankWrongToEnglish: "לא בדיוק. המשפט באנגלית הוא {answer}",
      sentenceBankCorrectToHebrew: "נכון. המשפט בעברית הוא {answer}",
      sentenceBankWrongToHebrew: "לא בדיוק. המשפט בעברית הוא {answer}",
      shemaCorrect: "נכון. שמעת {answer}",
      shemaWrong: "לא בדיוק. המשפט היה {answer}",
      shemaMeaning: "משמעות: {english}",
      sentenceBankSingleWordTip: "המילה הנכונה: {correctWord} = {correctMeaning}. המילה שנבחרה: {chosenWord} = {chosenMeaning}.",
      sentenceBankGameTip: "טיפ: {detail}",
      abbreviationCorrectToEnglish: 'נכון. {abbr} הוא הקיצור של "{english}".',
      abbreviationWrongToEnglish: 'לא בדיוק. {abbr} הוא הקיצור של "{english}".',
      abbreviationCorrectToHebrew: "נכון. הקיצור הוא {abbr}.",
      abbreviationWrongToHebrew: "לא בדיוק. הקיצור הוא {abbr}.",
      abbreviationExpansionDetail: "הניסוח המלא בעברית הוא {expansion}.",
      lessonDone: "השיעור הושלם. ציון סופי {score}/{total}.",
      reviewAdded: "נכללו סבבי הזדמנות שנייה: {count}.",
      startAnother: 'לחץ על "התחל תרגום" כדי להתחיל עוד סבב.',
      reviewIntro: "סבב הזדמנות שנייה: נסה שוב {count} מילים שפספסת.",
      matchDoneVerb: "הפועל הושלם: {verb}.",
      matchDoneAll: "אימון הנטיות הושלם. פעלים שכוסו: {count}.",
      advConjCorrectSentence: "נכון. המשפט הוא {answer}.",
      advConjWrongSentence: "לא בדיוק. המשפט הוא {answer}.",
      advConjMeaningDetail: "המשמעות המדוברת: {meaning}.",
      prepositionsCorrect: "נכון. זה {answer}.",
      prepositionsWrong: "לא בדיוק. התשובה היא {answer}.",
      prepositionsDetail: "משמעות: {meaning}.",
      binyanCorrect: "נכון: {form} פירושו {gloss}.",
      binyanWrong: "לא בדיוק: {form} פירושו {gloss}.",
    },
    summary: {
      resultsHeader: "סיכום אימון",
      lessonTitle: "תרגום הושלם",
      sentenceBankTitle: "משפטים הושלם",
      shemaTitle: "שמע הושלם",
      matchTitle: "נטיות הושלמו",
      abbreviationTitle: "ר״ת הושלמו",
      advConjTitle: "נטיות+ הושלמו",
      prepositionsTitle: "מילות יחס הושלמו",
      binyanTitle: "בניינים הושלמו",
      binyanNote: "שורשים שהושלמו: {roots}",
      handwritingTitle: "כתב יד הושלם",
      handwritingNote: "משפטים: {sentences}",
      score: "ציון: {score}/{total}",
      lessonNote: "סבבי הזדמנות שנייה: {count}",
      lessonNoteNone: "בסבב הזה לא היו סבבי הזדמנות שנייה.",
      matchNote: "פעלים: {verbs} | קומבו שיא: {combo} | זמן: {seconds}ש׳",
      abbreviationNote: "סבבים: {rounds} | זמן: {seconds}ש׳",
      wordMatchNote: "הותאמו: {matched} | קומבו שיא: {combo} | זמן: {seconds}ש׳",
      thumbsText: "כל הכבוד",
    },
    review: {
      queueEyebrow: "תור נקמה",
      queueTitle: "תור סקירה",
      queueEmpty: "אין פריטים שמחכים כרגע.",
      pending: "{count} פריטים מחכים למצב נקמה.",
      empty: "אין כרגע פריטים בתור הסקירה הפעיל.",
      analyticsEyebrow: "ניתוח קטגוריות",
      analyticsTitle: "ביצועים לפי קטגוריה",
      missedTitle: "טעויות לנקמה",
    },
    settings: {
      title: "הגדרות",
      note: "התאם שפה, ערכת נושא, אפקטים קוליים, דיבור וניקוד מובנה.",
      language: "שפה",
      feedbackSurvey: "שאלון משוב",
      niqqud: "ניקוד מובנה",
      theme: "ערכת נושא",
      resetTitle: "איפוס התקדמות",
      resetNote: "נקה שמירות, רצפים ונתוני סקירה.",
    },
    welcome: {
      title: "ברוך הבא ל-IvritElite!",
      line1: "זאת אפליקציה חדשה ללימוד עברית ברמה מתקדמת.",
      surveyPrefix: "נשמח לשמוע את המשוב שלך ב",
      surveyLink: "שאלון הזה",
      surveySuffix: ".",
      line2: "אפשר גם לגשת לשאלון מעמוד ההגדרות.",
      close: "סגור",
      closeAria: "סגור הודעת פתיחה",
    },
    results: {
      continue: "שחק שוב",
      correct: "נכון",
      incorrect: "שגוי",
      time: "זמן",
      score: "ציון",
      accuracy: "דיוק",
      reviewRounds: "סבבי חזרה",
      rounds: "סבבים",
      verbs: "פעלים",
      bestCombo: "הקומבו הטוב ביותר",
      mistakes: "טעויות מהסשן",
      mistakeClinic: "קליניקת טעויות",
      correctAnswers: "תשובות נכונות",
      clinic: "{note}",
      sentenceClinic: "טיפ: {note}",
      prepositionClinic: "תבנית: ‏{trigger} מצריך את {prep}; עם {object} משתמשים ב־{answer}.",
      advConjClinic: "בודקים שני חלקים: נושא {subject} בזמן {tense}, ומושא {object}.",
      binyanClinic: "תבנית: ‏{binyan} נושאת כאן {function}.",
      reviewPerformance: "סקירת ביצועים",
      niceJob: "כל הכבוד!",
      roomToImprove: "יש מקום לשיפור",
      amazing: "זה מדהים!",
      noMistakes: "לא היו טעויות בסשן הזה.",
      moreForms: "עוד {count}+",
    },
    match: {
      prompt: "התאם בין הזוגות",
      verbLabel: "פועל",
      leftColumn: "אנגלית",
      rightColumn: "עברית",
      progress: "זוגות: {current}/{total}",
      verbProgress: "פועל: {current}/{total}",
      timer: "זמן: {seconds}ש׳",
      combo: "קומבו x{count}",
      roundDone: "מעולה. התאמת את כל הנטיות עבור {verb}.",
      noVerbs: "לא נמצאו פעלים ברשימת אוצר המילים.",
      validatedNote: "נעשה שימוש בצורות מאומתות ושמורות עבור הפועל הזה.",
      generatedNote: "נעשה שימוש בצורות מחוללות ומאומתות עבור פועל שסומן בטוח להפקה.",
    },
    pool: {
      summary: "מאגר התרגום: {pool} מילים עם ניקוד ({total} בלקסיקון).",
      expansion: "מסלולי הרחבה שמופו: {count}.",
      tempProgress: "ההתקדמות זמנית בדפדפן זה (אחסון לא זמין).",
      fallback: "נטען אוצר מילים חלופי כי vocab-data.js לא היה זמין.",
    },
    missed: {
      title: "הלוח שפספסת הכי הרבה",
      note: "המילים שטעית בהן בתדירות הגבוהה ביותר.",
      empty: "עדיין אין פספוסים.",
      misses: "{count} פספוסים",
    },
    mastered: {
      open: "רשימת מנוסות",
      title: "מילים מנוסות",
      note: "מילים מנוסות יוצאות מסבבי תרגום אבל נשארות בסבבי נטיות.",
      selectHint: "סמן מילים שתרצה להחזיר לתרגול תרגום.",
      empty: "אין עדיין מילים מנוסות.",
      restoreSelected: "החזר מסומנות",
      close: "סגור",
      moveCurrent: "העבר למנוסות",
      streakStatus: "רצף נקי: {count}/{target}",
      ready: "הפועל {verb} הגיע ל-{target} סבבים נקיים. אפשר להעביר לרשימת מנוסות.",
      added: "{word} הועבר לרשימת מנוסות.",
      restored: "הוחזרו {count} מילים לתרגול תרגום.",
    },
    domain: {
      colloquial: "דיבורי ורחוב",
      everyday: "יומיומי ופונקציונלי",
      professional: "מקצועי",
      formal: "פורמלי ואנליטי",
    },
  },
};

bootstrapData.PERFORMANCE_DOMAINS = bootstrapData.PERFORMANCE_DOMAINS || [
  {
    id: "colloquial",
    emoji: "🗣️",
    label: "Colloquial & Street",
    categories: new Set([
      "conversation_glue",
      "dating_relationships",
      "relationships_dating_expanded",
      "media_digital_life_expanded",
      "emotional_nuance",
      "emotional_psychological_expanded",
      "social_cultural",
      "culture_identity_expanded",
    ]),
  },
  {
    id: "everyday",
    emoji: "🏠",
    label: "Everyday Functional",
    categories: new Set([
      "cooking_utensils",
      "cooking_verbs",
      "home_everyday_life",
      "everyday_survival_expanded",
      "health",
      "health_body_expanded",
      "bureaucracy",
    ]),
  },
  {
    id: "professional",
    emoji: "💼",
    label: "Professional",
    categories: new Set([
      "work_business",
      "business_finance_expanded",
      "finance_investing",
      "legal_civic",
      "law_legal_systems_expanded",
      "politics_society_expanded",
      "communication_mastery_expanded",
      "technology_ai",
      "technology_ai_expanded",
    ]),
  },
  {
    id: "formal",
    emoji: "📚",
    label: "Formal & Analytical",
    categories: new Set([
      "core_advanced",
      "abstract_philosophy",
      "abstract_concepts_expanded",
      "meta_language",
      "advanced_grammar_meta_expanded",
      "scientific_analytical",
      "science_research_expanded",
      "philosophy_intellectual_expanded",
      "high_level_discourse_expanded",
    ]),
  },
];

bootstrapData.DOMAIN_BY_CATEGORY = bootstrapData.DOMAIN_BY_CATEGORY || bootstrapData.buildDomainByCategoryMap(bootstrapData.PERFORMANCE_DOMAINS);
bootstrapData.FALLBACK_DOMAIN_ID = bootstrapData.FALLBACK_DOMAIN_ID || bootstrapData.PERFORMANCE_DOMAINS[bootstrapData.PERFORMANCE_DOMAINS.length - 1]?.id || "formal";
})(typeof window !== "undefined" ? window : globalThis);
